import {L,course,fact,quote,ui,hours} from './common.mjs';
const url='https://addicted2kite.webflow.io/',school=url+'lecole',prices=url+'tarif',booking=url+'contact';
export default {
 url,booking:{kind:'form',url:booking,text:L('Remplissez le formulaire officiel : coordonnées, poids, niveau, formule souhaitée, message et attestation de natation. L’équipe organise ensuite votre stage.','Complete the official form with contact details, weight, level, chosen course, message and swimming attestation. The team then arranges your course.','Fülle das offizielle Formular mit Kontaktdaten, Gewicht, Niveau, Kurswunsch, Nachricht und Schwimmbestätigung aus. Das Team organisiert anschließend deinen Kurs.','Completa el formulario oficial con contacto, peso, nivel, curso deseado, mensaje y declaración de natación. El equipo organizará tu curso.')},
 contacts:[{label:'schoolContact',phone:'+33674651701'}],
 intro:L('Deux spots entre Narbonne-Plage et Gruissan pour apprendre le kitesurf ou le wingfoil avec un suivi radio et bateau.','Two spots around Narbonne-Plage and Gruissan for kitesurf and wingfoil lessons with radio and boat support.','Zwei Spots bei Narbonne-Plage und Gruissan für Kite- und Wingfoilkurse mit Funk- und Bootsbetreuung.','Dos spots entre Narbonne-Plage y Gruissan para aprender kitesurf o wingfoil con apoyo de radio y embarcación.'),
 about:L('Fondée en 2015 par Julien et Laurent, Addicted2kite propose initiation, perfectionnement et location surveillée. Le site officiel annonce quatre élèves maximum par moniteur, un parking proche, une zone de rinçage, un shop et un espace détente.','Founded in 2015 by Julien and Laurent, Addicted2kite offers beginner lessons, progression and supervised rental. The official site lists at most four students per instructor, nearby parking, rinsing facilities, a shop and a relaxation area.','2015 von Julien und Laurent gegründet, bietet Addicted2kite Einsteigerkurse, Fortgeschrittenentraining und beaufsichtigten Verleih. Laut offizieller Website gibt es höchstens vier Schüler pro Lehrer, Parkplätze in der Nähe, einen Spülbereich, Shop und Aufenthaltsbereich.','Fundada en 2015 por Julien y Laurent, Addicted2kite ofrece iniciación, perfeccionamiento y alquiler supervisado. La web oficial indica un máximo de cuatro alumnos por instructor, aparcamiento cercano, zona de aclarado, tienda y zona de descanso.'),
 aboutSource:school,
 spot:L('Base au Créneau Naturel, D332, 11100 Narbonne-Plage, face à l’Aquajet. Le second spot est la Vieille Nouvelle, côté Gruissan. Les bateaux permettent la récupération et la remontée au vent.','The base is at Le Créneau Naturel, D332, 11100 Narbonne-Plage, opposite Aquajet. The second spot is La Vieille Nouvelle near Gruissan. Boats provide recovery and upwind transport.','Die Basis liegt am Créneau Naturel, D332, 11100 Narbonne-Plage, gegenüber Aquajet. Der zweite Spot ist La Vieille Nouvelle bei Gruissan. Boote übernehmen Rückholung und Transport gegen den Wind.','La base está en Le Créneau Naturel, D332, 11100 Narbonne-Plage, frente a Aquajet. El segundo spot es La Vieille Nouvelle, cerca de Gruissan. Las embarcaciones permiten recogida y transporte a barlovento.'),
 spotSource:school,mapQuery:'Créneau Naturel Aquajet Narbonne Plage France',
 priceNote:ui.datedRates,priceReferenceYear:2022,
 courses:[
  course(L('Initiation kitesurf','Beginner kitesurf','Kitesurf-Einstieg','Iniciación kitesurf'),quote,hours(3),prices,[L('Grille 2022 : 130 € / 135 € pour 1 séance ; 375 € / 390 € pour 3 séances, basse / haute saison.','2022 sheet: €130 / €135 for 1 session; €375 / €390 for 3 sessions, low / high season.','Preisliste 2022: 130 € / 135 € für 1 Einheit; 375 € / 390 € für 3 Einheiten, Neben- / Hauptsaison.','Tabla de 2022: 130 € / 135 € por 1 sesión; 375 € / 390 € por 3, temporada baja / alta.')]),
  course(L('Perfectionnement kitesurf','Kitesurf progression','Kitesurf-Aufbaukurs','Perfeccionamiento kitesurf'),quote,hours(3),prices,[L('Pour les riders ayant déjà glissé. Devis actuel via le formulaire officiel.','For riders who have already ridden a board. Request a current quote through the official form.','Für Kiter mit erster Fahrerfahrung. Aktuelles Angebot über das offizielle Formular.','Para quienes ya han deslizado sobre la tabla. Solicita presupuesto actual en el formulario oficial.')]),
  course('Wingsurf / Wingfoil',quote,hours(2),prices,[L('Grille 2022 : wingsurf 120 € / 130 € ; wingfoil 130 € / 140 €, basse / haute saison.','2022 sheet: wingsurf €120 / €130; wingfoil €130 / €140, low / high season.','Preisliste 2022: Wingsurf 120 € / 130 €; Wingfoil 130 € / 140 €, Neben- / Hauptsaison.','Tabla de 2022: wingsurf 120 € / 130 €; wingfoil 130 € / 140 €, temporada baja / alta.')]),
  course(L('Location et navigation surveillées','Supervised rental and riding','Beaufsichtigter Verleih und Kiten','Alquiler y navegación supervisados'),quote,hours(3),prices,[L('Grille 2022 : location surveillée 85 € / 90 € ; navigation surveillée 45 € / 50 €. Réservées aux autonomes.','2022 sheet: supervised rental €85 / €90; supervised riding €45 / €50. For independent riders.','Preisliste 2022: beaufsichtigter Verleih 85 € / 90 €; betreutes Kiten 45 € / 50 €. Für selbstständige Kiter.','Tabla de 2022: alquiler supervisado 85 € / 90 €; navegación supervisada 45 € / 50 €. Para riders autónomos.')]),
  course(L('Coaching, kitefoil et simulateur','Coaching, kitefoil and simulator','Coaching, Kitefoil und Simulator','Coaching, kitefoil y simulador'),quote,L('Autres formules de la grille officielle','More options in the official tariff sheet','Weitere Angebote in der offiziellen Preisliste','Más opciones en la tabla oficial'),prices)
 ],
 facts:[
  fact('requirements',L('Poids minimum indiqué : 40 kg, avec adaptation au cas par cas. Pour les enfants : attestation de natation et autorisation parentale. La responsabilité civile kite/wing est obligatoire ; justificatif demandé au début du stage.','Published minimum weight: 40 kg, subject to individual assessment. Children need swimming attestation and parental authorisation. Kite/wing liability insurance is compulsory; bring proof for the start of the course.','Angegebenes Mindestgewicht: 40 kg, mit Einzelfallprüfung. Kinder benötigen Schwimmbestätigung und elterliche Genehmigung. Kite-/Wing-Haftpflicht ist Pflicht; Nachweis zum Kursbeginn mitbringen.','Peso mínimo publicado: 40 kg, valorado individualmente. Los menores necesitan declaración de natación y autorización parental. El seguro de responsabilidad civil kite/wing es obligatorio; presenta el justificante al comenzar.'),url),
  fact('prices',ui.datedRates,prices),
  fact('equipment',L('Chaque élève est suivi par radio. Le site décrit deux bateaux et des cours utilisant la plage, l’eau peu profonde puis la mer selon les exercices. Les progrès dépendent de chaque élève.','Students receive radio coaching. The site describes two boats and lessons using the beach, shallow water and the sea depending on the exercise. Progress varies by student.','Funkbetreuung für die Schüler. Die Website nennt zwei Boote und Unterricht am Strand, im flachen Wasser und auf dem Meer je nach Übung. Der Fortschritt ist individuell.','Los alumnos reciben seguimiento por radio. La web describe dos embarcaciones y ejercicios en playa, aguas poco profundas y mar. La progresión depende de cada alumno.'),school)
 ],
 links:[{label:'insurance',url:'https://www.air-assurances.com/formafkite.asp?ecole=11004'},{label:'weather',url:'https://www.windguru.cz/242'},{label:'lodging',url:url+'hebergement'},{label:'team',url:school},{label:'photos',url}],
 sources:[{label:'official',url},{label:'team',url:school},{label:'prices',url:prices},{label:'form',url:booking}]
};
