import {L,course,fact,quote} from './common.mjs';
const url='https://www.chinook-leucate.com/',school='https://chinook-leucate.blog/tag/chinook-kiteschool/';
export default {
 url,booking:{kind:'phone',url:'tel:+33468401717',text:L('Appelez le shop pour confirmer les cours, le moniteur, les dates et les tarifs actuels. L’annonce école de 2024 donne aussi le contact direct de Philippe Blondé : 06 30 82 09 52.','Call the shop to confirm current lessons, instructor, dates and prices. The school’s 2024 announcement also gives Philippe Blondé’s direct number: +33 6 30 82 09 52.','Rufe den Shop an, um aktuelle Kurse, Lehrer, Termine und Preise zu bestätigen. Die Schulmeldung von 2024 nennt auch Philippe Blondés Direktnummer: +33 6 30 82 09 52.','Llama a la tienda para confirmar cursos, instructor, fechas y precios actuales. El anuncio de la escuela de 2024 también da el teléfono directo de Philippe Blondé: +33 6 30 82 09 52.')},
 contacts:[{label:'shopContact',phone:'+33468401717',email:'contact@chinook-leucate.com'},{label:L('Philippe — annonce école 2024','Philippe — 2024 school notice','Philippe — Schulmeldung 2024','Philippe — anuncio de 2024'),phone:'+33630820952'}],
 intro:L('La glisse à Leucate : un shop spécialisé et une école présentée sur le spot de l’étang de La Palme.','Board sports in Leucate: a specialist shop and a school presented at the Étang de La Palme spot.','Boardsport in Leucate: ein Fachshop und eine Schule, die den Étang de La Palme als Spot vorstellt.','Deportes de deslizamiento en Leucate: una tienda especializada y una escuela presentada en el estanque de La Palme.'),
 about:L('Dans son annonce de saison 2024, Chinook présente Philippe Blondé, dit Philou, pour débuter et progresser en kite à La Palme. Le shop reste le point de contact actuel pour confirmer l’activité école et trouver du matériel de kitesurf, windsurf, wing et surf.','In its 2024 season announcement, Chinook presents Philippe Blondé, known as Philou, for beginner and progression kite lessons at La Palme. The shop is the current contact for confirming school activity and finding kite, windsurf, wing and surf equipment.','In der Saisonmeldung 2024 stellt Chinook Philippe Blondé, genannt Philou, für Kite-Einstieg und Fortschritt in La Palme vor. Der Shop ist der aktuelle Kontakt zur Bestätigung des Schulbetriebs und für Kite-, Windsurf-, Wing- und Surfmaterial.','En su anuncio de temporada 2024, Chinook presenta a Philippe Blondé, conocido como Philou, para iniciación y progresión en La Palme. La tienda es el contacto actual para confirmar la actividad de la escuela y encontrar material de kite, windsurf, wing y surf.'),
 aboutSource:school,
 spot:L('L’annonce école situe les cours sur l’étang de La Palme, en eau peu profonde. Confirmez le lieu et l’heure de rendez-vous avec le shop ou Philippe avant de vous déplacer ; le magasin et le spot sont deux lieux différents.','The school notice places lessons on shallow-water Étang de La Palme. Confirm the meeting place and time with the shop or Philippe before travelling; the shop and teaching spot are separate places.','Die Schulmeldung nennt den flachen Étang de La Palme als Unterrichtsspot. Treffpunkt und Uhrzeit vor der Anreise mit Shop oder Philippe bestätigen; Shop und Schulungsspot sind verschiedene Orte.','El anuncio sitúa las clases en las aguas poco profundas del estanque de La Palme. Confirma lugar y hora con la tienda o Philippe antes de desplazarte; tienda y spot son lugares diferentes.'),
 spotSource:school,mapQuery:'Etang de La Palme France',
 priceNote:L('Aucune grille école récente vérifiée. Demandez un devis au shop ; les prix du catalogue concernent du matériel, pas des cours.','No recent school tariff sheet was verified. Ask the shop for a quote; catalogue prices are for equipment, not lessons.','Keine aktuelle Schulpreisliste verifiziert. Frage den Shop nach einem Angebot; Katalogpreise gelten für Material, nicht für Kurse.','No se ha verificado una tabla reciente de la escuela. Pide presupuesto a la tienda; los precios del catálogo son de material, no de cursos.'),
 courses:[
  course(L('Initiation','Beginner lessons','Einsteigerkurse','Iniciación'),quote,L('Programme à confirmer avec l’école','Confirm the programme with the school','Programm mit der Schule bestätigen','Confirma el programa con la escuela'),school),
  course(L('Progression et perfectionnement','Progression and coaching','Aufbaukurse und Coaching','Progresión y perfeccionamiento'),quote,L('Objectifs et durée sur demande','Goals and duration on enquiry','Ziele und Dauer auf Anfrage','Objetivos y duración a consultar'),school),
  course(L('Matériel et conseils du shop','Shop equipment and advice','Material und Beratung im Shop','Material y asesoramiento de la tienda'),quote,L('Catalogue, commande et compte client officiels','Official catalogue, orders and customer account','Offizieller Katalog, Bestellungen und Kundenkonto','Catálogo, pedidos y cuenta de cliente oficiales'),url,[],url)
 ],
 facts:[
  fact('schedule',L('Shop : 195 avenue du Général de Gaulle, 11370 Leucate. Horaires publiés : mardi–samedi 9h30–13h et 15h30–19h ; dimanche 9h30–13h ; lundi fermé. Cours sur rendez-vous.','Shop: 195 avenue du Général de Gaulle, 11370 Leucate. Published hours: Tuesday–Saturday 09:30–13:00 and 15:30–19:00; Sunday 09:30–13:00; Monday closed. Arrange lessons directly.','Shop: 195 avenue du Général de Gaulle, 11370 Leucate. Veröffentlichte Zeiten: Dienstag–Samstag 9:30–13 und 15:30–19 Uhr; Sonntag 9:30–13 Uhr; Montag geschlossen. Kurse nach Vereinbarung.','Tienda: 195 avenue du Général de Gaulle, 11370 Leucate. Horario publicado: martes–sábado 9:30–13 y 15:30–19; domingo 9:30–13; lunes cerrado. Clases con cita previa.'),url+'magasins'),
  fact('requirements',L('Faites préciser le matériel fourni, les prérequis, l’assurance et les conditions d’annulation lors de la réservation.','Ask what equipment is included and confirm prerequisites, insurance and cancellation terms when booking.','Bei der Buchung enthaltene Ausrüstung, Voraussetzungen, Versicherung und Stornobedingungen klären.','Al reservar, consulta equipo incluido, requisitos, seguro y cancelación.'),url+'nous-contacter'),
  fact('shop',L('Le site officiel permet de consulter le catalogue, commander du matériel et gérer son compte client. Pour une question école, appelez le shop au lieu de chercher un cours dans le panier matériel.','The official site has an equipment catalogue, ordering and customer accounts. For school enquiries, call the shop rather than using the equipment shopping cart.','Die offizielle Website bietet Materialkatalog, Bestellung und Kundenkonto. Bei Schulfragen den Shop anrufen; der Materialwarenkorb dient nicht der Kursbuchung.','La web oficial permite consultar el catálogo, comprar material y gestionar una cuenta. Para cursos, llama a la tienda; el carrito de material no sirve para reservar clases.'),url)
 ],
 links:[{label:'shop',url},{label:'schedule',url:url+'magasins'},{label:'weather',url:url+'content/7-meteo'},{label:'photos',url:school}],
 sources:[{label:'shop',url},{label:'team',url:school},{label:'schedule',url:url+'magasins'}]
};
