import {L,course,fact,quote,ui,hours} from './common.mjs';
const url='https://coriolisfoilschool.fr/',booking=url+'contact/',wake=url+'wake-foil-leucate/',wing=url+'cours-wing-foil-leucate/',kite=url+'kite-foil-leucate/';
export default {
 url,booking:{kind:'form',url:booking,text:L('Inscription via le formulaire officiel : nom, e-mail, téléphone, discipline, taille, poids et message. Luc vous aide à choisir votre parcours. Pour les créneaux et les tarifs actuels, contactez directement l’école.','Register through the official form: name, email, phone, discipline, height, weight and message. Luc helps you choose a learning path. Contact the school for current times and prices.','Anmeldung über das offizielle Formular: Name, E-Mail, Telefon, Disziplin, Größe, Gewicht und Nachricht. Luc hilft bei der Kurswahl. Aktuelle Termine und Preise direkt mit der Schule klären.','Inscríbete mediante el formulario oficial: nombre, correo, teléfono, disciplina, altura, peso y mensaje. Luc te ayuda a elegir el recorrido. Consulta horarios y precios actuales con la escuela.')},
 contacts:[{label:'schoolContact',phone:'+33662070867'}],
 intro:L('Simulateur tracté, wingfoil et kitefoil entre les spots de La Mine et du Petit Pêcheur, sur l’étang de Leucate.','Boat-towed simulator, wingfoil and kitefoil around La Mine and Le Petit Pêcheur on Étang de Leucate.','Bootsgezogener Simulator, Wingfoil und Kitefoil bei La Mine und Le Petit Pêcheur am Étang de Leucate.','Simulador remolcado, wingfoil y kitefoil entre La Mine y Le Petit Pêcheur, en el estanque de Leucate.'),
 about:L('Luc Graulou présente une progression adaptée à votre expérience de glisse. Le simulateur permet de travailler l’équilibre sur le foil sans gérer une aile. L’école propose ensuite des séances et des packs de wingfoil ou de kitefoil.','Luc Graulou adapts progression to your board-sports experience. The simulator lets you practise foil balance without handling a kite or wing. The school then offers wingfoil and kitefoil sessions and packages.','Luc Graulou passt den Lernweg an deine Boardsporterfahrung an. Der Simulator ermöglicht Gleichgewichtstraining auf dem Foil ohne Kite oder Wing. Danach gibt es Wingfoil- und Kitefoil-Einheiten und Pakete.','Luc Graulou adapta la progresión a tu experiencia. El simulador permite trabajar el equilibrio en el foil sin manejar cometa o wing. Después se ofrecen sesiones y paquetes de wingfoil o kitefoil.'),
 aboutSource:url+'notre-moniteur/',
 spot:L('La base et le parking se situent près du Petit Pêcheur. Le site indique simulateur et wingfoil au Petit Pêcheur par marin, et wingfoil à La Mine par tramontane, avec transfert bateau. Faites confirmer le spot de votre séance.','The base and parking are near Le Petit Pêcheur. The site lists simulator and wingfoil at Le Petit Pêcheur in marin wind, and wingfoil at La Mine in tramontane, reached by boat. Confirm your session’s spot.','Basis und Parkplatz liegen bei Le Petit Pêcheur. Laut Website finden dort Simulator und Wingfoil bei Marin statt; bei Tramontane geht es zum Wingfoilen per Boot nach La Mine. Lass deinen Spot bestätigen.','La base y el aparcamiento están junto a Le Petit Pêcheur. La web indica simulador y wingfoil allí con viento marin, y wingfoil en La Mine con tramontana, accediendo en barco. Confirma el spot de tu sesión.'),
 spotSource:booking,mapUrl:'https://goo.gl/maps/t6eAqGpa5kVQWbQN9',
 priceNote:ui.datedRates,priceReferenceYear:2022,
 referenceRates:[{name:L('Simulateur — 45 min','Simulator — 45 min','Simulator — 45 Min.','Simulador — 45 min'),price:'100 € / 120 €'},{name:L('Pack 3 × 45 min','Pack 3 × 45 min','Paket 3 × 45 Min.','Paquete 3 × 45 min'),price:'280 € / 340 €'}],referenceSource:wake,
 courses:[
  course(L('Simulateur / wakefoil','Simulator / wakefoil','Simulator / Wakefoil','Simulador / wakefoil'),quote,'45 min',wake,[L('3 personnes maximum selon la grille officielle. Apprentissage des appuis, à genoux puis debout.','At most 3 people according to the official sheet. Practise balance on your knees, then standing.','Höchstens 3 Personen laut offizieller Liste. Gleichgewicht zunächst kniend, danach stehend üben.','Máximo 3 personas según la tabla oficial. Trabajo del equilibrio de rodillas y luego de pie.')]),
  course(L('Pack 3 séances simulateur','Three-session simulator pack','Simulator-Paket mit 3 Einheiten','Paquete de 3 sesiones de simulador'),quote,'3 × 45 min',wake),
  course(L('Wingfoil — séance','Wingfoil session','Wingfoil-Einheit','Sesión wingfoil'),quote,hours(2),wing),
  course(L('Packs wingfoil','Wingfoil packages','Wingfoil-Pakete','Paquetes wingfoil'),quote,L('Découverte, rider ou voileux','Discovery, rider or sailor','Einstieg, Rider oder Segler','Descubrimiento, rider o navegante'),wing,[L('Découverte : 1 simulateur + 1 wing ; rider : 1 simulateur + 2 wing ; voileux : 2 simulateurs + 1 wing.','Discovery: 1 simulator + 1 wing; rider: 1 simulator + 2 wing; sailor: 2 simulator + 1 wing.','Einstieg: 1 Simulator + 1 Wing; Rider: 1 Simulator + 2 Wing; Segler: 2 Simulator + 1 Wing.','Descubrimiento: 1 simulador + 1 wing; rider: 1 simulador + 2 wing; navegante: 2 simulador + 1 wing.')]),
  course(L('Kitefoil — séance et packs','Kitefoil sessions and packs','Kitefoil-Einheiten und Pakete','Sesiones y paquetes kitefoil'),quote,hours(2),kite,[L('Cours particuliers adaptés au niveau en kitesurf ; pack découverte et pack perfectionnement de 3 séances.','Private lessons adapted to kitesurf experience; discovery pack and three-session progression pack.','Privatkurse passend zum Kitesurfniveau; Entdeckerpaket und Aufbaupaket mit 3 Einheiten.','Clases particulares adaptadas al nivel de kitesurf; paquete de descubrimiento y de perfeccionamiento de 3 sesiones.')])
 ],
 facts:[
  fact('schedule',L('Ouverture indiquée : 7 j/7, du 1er avril au 30 novembre. Les séances dépendent des conditions et du planning de l’école.','Published season: daily, 1 April–30 November. Sessions depend on conditions and the school’s schedule.','Angegebene Saison: täglich, 1. April–30. November. Einheiten hängen von Bedingungen und Schulplan ab.','Apertura publicada: todos los días del 1 de abril al 30 de noviembre. Las sesiones dependen de condiciones y calendario de la escuela.'),booking),
  fact('requirements',L('Consultez la page assurance et les documents de l’école avant de vous inscrire. Le formulaire demande taille et poids pour préparer un matériel adapté. L’école accueille les enfants dès 10 ans selon ses informations pédagogiques.','Read the school’s insurance page and documents before registering. The form requests height and weight to prepare suitable equipment. The school’s teaching information welcomes children from age 10.','Vor Anmeldung Versicherungsseite und Schulunterlagen lesen. Das Formular erfragt Größe und Gewicht für passende Ausrüstung. Laut Schulinformationen sind Kinder ab 10 Jahren willkommen.','Consulta la página de seguro y los documentos antes de inscribirte. El formulario pide altura y peso para preparar equipo adecuado. La información pedagógica admite niños desde los 10 años.'),url+'nos-valeurs/'),
  fact('prices',L('La grille simulateur est titrée « Nos formules 2022 ». Elle distingue basse saison et juillet–août. Retrouvez les montants de référence ci-dessus ; faites confirmer le prix de votre réservation.','The simulator sheet is headed “2022 packages”. It separates low season and July–August. See the reference amounts above; confirm the price for your booking.','Die Simulatorliste trägt den Titel „Angebote 2022“ und unterscheidet Nebensaison und Juli–August. Oben stehen die historischen Beträge; aktuellen Buchungspreis bestätigen lassen.','La tabla del simulador se titula «Fórmulas 2022» y distingue temporada baja y julio–agosto. Consulta arriba los importes de referencia y confirma el precio de tu reserva.'),wake)
 ],
 links:[{label:'insurance',url:url+'assurance/'},{label:'arrival',url:'https://goo.gl/maps/Cdu6DoRGUyDNeYsXA'},{label:'team',url:url+'notre-moniteur/'},{label:'photos',url}],
 sources:[{label:'official',url},{label:'prices',url:wake},{label:'courses',url:wing},{label:'form',url:booking}]
};
