import {L,course,fact,quote,seasonal,hours} from './common.mjs';
const url='https://kitepulsion.com/';
export default {
 url,booking:{kind:'email',url:'mailto:kitepulsion@gmail.com',text:L('Envoyez vos dates, votre niveau et vos objectifs à Thomas. L’école vous recontacte pour organiser le stage.','Email Thomas your dates, level and goals. The school will contact you to arrange the course.','Schicke Thomas deine Termine, dein Niveau und deine Ziele. Die Schule meldet sich zur Kursplanung.','Envía a Thomas tus fechas, nivel y objetivos. La escuela te contactará para organizar el curso.')},
 contacts:[{label:'schoolContact',phone:'+33682314920',email:'kitepulsion@gmail.com'}],
 intro:L('Kitesurf aux Coussoules, à La Franqui : des cours en petits groupes, un suivi radio et une assistance Zodiac.','Kitesurf at Les Coussoules in La Franqui, with small groups, radio coaching and Zodiac support.','Kitesurfen an den Coussoules in La Franqui: kleine Gruppen, Funkbetreuung und Zodiac-Unterstützung.','Kitesurf en Les Coussoules, La Franqui: grupos pequeños, seguimiento por radio y apoyo en Zodiac.'),
 about:L('Thomas Kraemer enseigne à Leucate depuis 2002. Moniteur et entraîneur diplômé BPJEPS et DEJEPS Kite, il propose des cours en français, anglais et allemand. Freestyle, strapless et foil complètent l’initiation.','Thomas Kraemer has taught in Leucate since 2002. A BPJEPS- and DEJEPS-qualified kite instructor and coach, he teaches in French, English and German. Freestyle, strapless and foil complement beginner lessons.','Thomas Kraemer unterrichtet seit 2002 in Leucate. Der BPJEPS- und DEJEPS-Kite-Lehrer und Trainer unterrichtet auf Französisch, Englisch und Deutsch. Neben Einsteigerkursen gibt es Freestyle, Strapless und Foil.','Thomas Kraemer enseña en Leucate desde 2002. Instructor y entrenador con títulos BPJEPS y DEJEPS Kite, imparte cursos en francés, inglés y alemán, desde iniciación hasta freestyle, strapless y foil.'),
 aboutSource:url,
 spot:L('La plage des Coussoules à La Franqui permet de travailler en eau peu profonde puis en pleine eau avec assistance bateau. Le lieu et l’horaire exacts sont communiqués la veille à 20 h, selon la météo.','Les Coussoules beach at La Franqui offers shallow-water practice and open-water teaching with boat support. The exact meeting place and time are sent at 20:00 the previous evening, depending on the weather.','Am Strand Les Coussoules in La Franqui wird im flachen und offenen Wasser mit Bootsunterstützung geübt. Genauen Treffpunkt und Uhrzeit teilt die Schule am Vorabend um 20 Uhr je nach Wetter mit.','En la playa de Les Coussoules, La Franqui, se practica en aguas poco profundas y en mar abierto con apoyo de embarcación. El lugar y la hora exactos se comunican a las 20:00 del día anterior según la meteorología.'),
 spotSource:url,mapQuery:'Plage des Coussoules La Franqui Leucate France',
 courses:[
  course('À la carte','130 € / 150 €',seasonal,url,[L('3 h en groupe, 3 élèves maximum par moniteur.','3-hour group lesson, at most 3 students per instructor.','3 Stunden in der Gruppe, höchstens 3 Schüler pro Lehrer.','Curso de 3 horas, máximo 3 alumnos por instructor.')]),
  course('Flexibilité','130 € / 150 €',seasonal,url,[L('Au choix : collectif 3 h, individuel 1 h, ou privé à deux 2 h. Prix par personne.','Choose a 3-hour group lesson, 1-hour individual lesson, or 2-hour private lesson for two. Price per person.','Zur Wahl: 3 Stunden Gruppenkurs, 1 Stunde Einzelkurs oder 2 Stunden Privatkurs zu zweit. Preis pro Person.','Elige: grupo de 3 h, individual de 1 h o privado para dos de 2 h. Precio por persona.')]),
  course(L('Cours particulier','Private coaching','Privatunterricht','Clase particular'),quote,L('Programme personnalisé','Personal programme','Individuelles Programm','Programa personalizado'),url,[L('Créneau météo adapté et analyse vidéo.','Weather-adapted timing and video analysis.','Wetterangepasster Termin und Videoanalyse.','Horario adaptado al tiempo y análisis de vídeo.')]),
  course(L('Coaching perfectionnement','Progression coaching','Fortgeschrittenentraining','Entrenamiento avanzado'),quote,L('Groupe de 4 à 6 riders autonomes','Group of 4–6 independent riders','Gruppe mit 4–6 selbstständigen Kitern','Grupo de 4–6 riders autónomos'),url,[L('Freestyle, strapless, nouveaux supports et analyse vidéo.','Freestyle, strapless, new disciplines and video analysis.','Freestyle, Strapless, neue Disziplinen und Videoanalyse.','Freestyle, strapless, nuevas disciplinas y análisis de vídeo.')])
 ],
 facts:[
  fact('prices',L('130 € par personne hors juillet–août ; 150 € en juillet–août pour les formules à la carte et flexibilité.','€130 per person outside July–August; €150 in July–August for the à-la-carte and flexible options.','130 € pro Person außerhalb Juli–August; 150 € im Juli–August für À-la-carte- und flexible Angebote.','130 € por persona fuera de julio–agosto; 150 € en julio–agosto para las fórmulas a la carta y flexibilidad.'),url),
  fact('requirements',L('Licence/assurance FFVL spécifique obligatoire, non incluse. Consultez les garanties et tarifs en vigueur avant le stage. Prévoir chaussons, protection solaire, eau et en-cas. Prêt de combinaison à demander à l’inscription.','Specific FFVL licence/insurance is compulsory and excluded. Check current cover and fees before the course. Bring neoprene boots, sun protection, water and a snack. Request a wetsuit loan when registering.','Eine spezielle FFVL-Lizenz/Versicherung ist Pflicht und nicht enthalten. Prüfe aktuelle Leistungen und Beiträge vor dem Kurs. Neoprenschuhe, Sonnenschutz, Wasser und Snack mitbringen; Neoprenanzug bei Anmeldung anfragen.','La licencia/seguro específico FFVL es obligatorio y no está incluido. Consulta coberturas y tarifas vigentes antes del curso. Lleva escarpines, protección solar, agua y algo de comer. Solicita el préstamo de neopreno al inscribirte.'),url),
  fact('schedule',L('En cas de météo défavorable : report ou remboursement. Les reports non effectués pour manque de conditions restent valables un an. Powerkite, catakite et glisse tractée sont aussi proposés ; snowkite en hiver.','Unsuitable weather: postponement or refund. Weather-related unused sessions remain valid for one year. Powerkite, catakite and boat-towed activities are also offered, with snowkite in winter.','Bei ungeeignetem Wetter: Verschiebung oder Erstattung. Wetterbedingt ausgefallene Einheiten bleiben ein Jahr gültig. Auch Powerkite, Catakite und bootsgezogene Aktivitäten; im Winter Snowkite.','Con meteorología desfavorable: aplazamiento o reembolso. Las sesiones pendientes por mal tiempo son válidas un año. También se ofrecen powerkite, catakite y actividades remolcadas; snowkite en invierno.'),url)
 ],
 links:[{label:'insurance',url:'https://federation.ffvl.fr/'},{label:'photos',url}],
 sources:[{label:'official',url}]
};
