import {L,course,fact,quote} from './common.mjs';
const url='https://www.kite-surf-leucate.com/',booking=url+'inscription-r%C3%A9servation-cours-kite-wing',teams=url+'copie-de-les-teams',safety=url+'s%C3%A9curit%C3%A9';
const instructor=L('Moniteur BPJEPS','BPJEPS instructor','BPJEPS-Lehrer','Instructor BPJEPS');
export default {
 url,booking:{kind:'form',url:booking,text:L('Utilisez la page officielle d’inscription et son formulaire, ou appelez l’école pour les cours. Pour sécurité, location et vie du club, utilisez les coordonnées du club ci-dessous.','Use the official registration page and its form, or call the school for lessons. For safety support, rental and club activities, use the separate club contacts below.','Nutze die offizielle Anmeldeseite mit Formular oder rufe die Schule für Kurse an. Für Sicherheit, Verleih und Clubleben gelten die separaten Clubkontakte unten.','Utiliza la página oficial de inscripción y su formulario, o llama a la escuela para clases. Para seguridad, alquiler y actividades del club, usa el contacto del club indicado abajo.')},
 contacts:[{label:'schoolContact',phone:'+33611581614',email:'ecole.kitesurfleucate@gmail.com'},{label:'clubContact',phone:'+33619959802',email:'contact.kitesurfleucate@gmail.com'}],
 intro:L('À La Franqui, KSL réunit une école de kite, wing et foil et un club de pratiquants depuis 2004.','At La Franqui, KSL combines a kite, wing and foil school with a riders’ club founded in 2004.','In La Franqui verbindet KSL seit 2004 eine Kite-, Wing- und Foilschule mit einem Sportclub.','En La Franqui, KSL reúne una escuela de kite, wing y foil y un club de practicantes desde 2004.'),
 about:L('L’école accompagne l’apprentissage ; le club organise location, assistance sur le spot et entraînement des jeunes. Les équipes jeunes et performance ont leurs propres saisons et horaires. Les deux contacts sont distincts pour vous orienter vers la bonne équipe.','The school teaches; the club handles rental, spot assistance and youth training. Youth and performance teams have their own seasons and schedules. Separate contact details connect you to the right team.','Die Schule unterrichtet; der Club organisiert Verleih, Unterstützung am Spot und Jugendtraining. Jugend- und Leistungsteams haben eigene Saisons und Zeiten. Separate Kontakte führen dich zum richtigen Team.','La escuela imparte cursos; el club gestiona alquiler, asistencia y entrenamiento juvenil. Los equipos juvenil y de rendimiento tienen temporadas y horarios propios. Los contactos separados permiten dirigirte al equipo adecuado.'),
 aboutSource:url,
 spot:L('Plage des Coussoules, 11370 La Franqui. Par tramontane, le club propose une assistance sur une zone définie ; vérifiez le forfait, les limites de navigation et les horaires directement auprès du club avant de naviguer.','Plage des Coussoules, 11370 La Franqui. In tramontane wind the club provides assistance in a defined area; check the package, navigation limits and hours with the club before riding.','Plage des Coussoules, 11370 La Franqui. Bei Tramontane bietet der Club Hilfe in einem definierten Gebiet. Vor dem Kiten Paket, Reviergrenzen und Zeiten beim Club prüfen.','Plage des Coussoules, 11370 La Franqui. Con tramontana, el club ofrece asistencia en una zona definida; comprueba tarifa, límites de navegación y horarios con el club antes de salir.'),
 spotSource:safety,mapQuery:'Kite Surf Leucate Les Coussoules La Franqui France',
 courses:[
  course('Kitesurf',quote,L('Cours et stages','Lessons and courses','Kurse und Camps','Clases y cursos'),url+'kitesurf'),
  course('Wing / foil',quote,L('Cours avec l’école','Lessons with the school','Unterricht bei der Schule','Clases con la escuela'),url+'s-projects-side-by-side'),
  course(L('Tractée, simulateur et terrestre','Towed, simulator and land sessions','Gezogene, Simulator- und Landeinheiten','Remolque, simulador y actividades terrestres'),quote,L('Disciplines présentées sur le site officiel','Disciplines listed on the official site','Disziplinen auf der offiziellen Website','Disciplinas de la web oficial'),url),
  course(L('Team Jeunes / Team Performance','Youth / Performance teams','Jugend- / Leistungsteam','Equipo juvenil / rendimiento'),quote,L('Jeunes dès 8 ans ; performance 8–18 ans','Youth from age 8; performance ages 8–18','Jugend ab 8; Leistungsteam 8–18 Jahre','Juvenil desde 8 años; rendimiento 8–18 años'),teams),
  course(L('Location et sécurité du club','Club rental and safety support','Clubverleih und Sicherheitsservice','Alquiler y seguridad del club'),quote,L('Contacter le club, pas le numéro école','Use the club contact, not the school number','Den Clubkontakt nutzen, nicht die Schulnummer','Contacta con el club, no con el número de la escuela'),safety,[],'tel:+33619959802')
 ],
 facts:[
  fact('schedule',L('École : tous les jours sur réservation, fermeture annuelle du 15 décembre au 15 janvier. Sécurité/location : jours de tramontane, avril–octobre, 9–17 h ; week-ends jusqu’à 19 h ; juillet–août jusqu’à 20 h.','School: daily by reservation; annual closure 15 December–15 January. Safety/rental: tramontane days, April–October, 09:00–17:00; weekends until 19:00; July–August until 20:00.','Schule: täglich nach Buchung, jährliche Schließung 15. Dezember–15. Januar. Sicherheit/Verleih: Tramontanetage April–Oktober, 9–17 Uhr; Wochenende bis 19 Uhr, Juli–August bis 20 Uhr.','Escuela: todos los días con reserva, cierre anual 15 de diciembre–15 de enero. Seguridad/alquiler: días de tramontana, abril–octubre, 9–17 h; fines de semana hasta 19 h; julio–agosto hasta 20 h.'),booking),
  fact('requirements',L('Confirmez niveau, matériel, assurance et conditions auprès de l’école pour les cours, ou du club pour la navigation autonome. Pour une séance adaptée ou une demande handikite, demandez au club les possibilités actuelles.','Confirm level, equipment, insurance and conditions with the school for lessons, or the club for independent riding. Ask the club about current options for adaptive sessions or handikite.','Niveau, Material, Versicherung und Bedingungen für Kurse mit der Schule, für selbstständiges Kiten mit dem Club klären. Den Club nach aktuellen Möglichkeiten für angepasste Einheiten oder Handikite fragen.','Confirma nivel, material, seguro y condiciones con la escuela para clases, o con el club para navegación autónoma. Consulta al club las opciones actuales de sesiones adaptadas o handikite.'),booking),
  fact('team',L('Team Jeunes : avril–octobre, mercredis et samedis, uniquement le samedi en juillet–août. Team Performance : septembre–juin, mercredis et samedis. Consultez le club pour l’inscription.','Youth team: April–October, Wednesdays and Saturdays; Saturdays only in July–August. Performance team: September–June, Wednesdays and Saturdays. Contact the club to join.','Jugendteam: April–Oktober, mittwochs und samstags; im Juli–August nur samstags. Leistungsteam: September–Juni, mittwochs und samstags. Anmeldung beim Club.','Equipo juvenil: abril–octubre, miércoles y sábados; solo sábados en julio–agosto. Rendimiento: septiembre–junio, miércoles y sábados. Inscripción mediante el club.'),teams)
 ],
 team:[{name:'Bernard Brigasco',role:L('Président','President','Präsident','Presidente')},{name:'Thomas Civier',role:L('Responsable de base','Base manager','Basisleiter','Responsable de base')},{name:'Guillaume Lips',role:instructor},{name:'Cédric Sicard',role:instructor},{name:'Robin Ambrosi',role:instructor},{name:'Thomas Lopin',role:instructor},{name:'Antoine Aubert',role:instructor},{name:'Lilou Broutin',role:L('Accueil','Reception','Empfang','Recepción')},{name:'Eliot Sicard',role:L('Sécurité en mer','Sea safety','Sicherheit auf See','Seguridad en el mar')}],
 links:[{label:'team',url:teams},{label:'photos',url},{label:'weather',url},{label:'prices',url:safety}],
 sources:[{label:'official',url},{label:'form',url:booking},{label:'team',url:teams},{label:'prices',url:safety}]
};
