import {L,course,fact,quote,hours} from './common.mjs';
const url='http://www.osmose-kite.com/',booking=url+'reservation/',prices=url+'tarifs/';
const seasons=L('Basse saison / juillet–août / hiver','Low season / July–August / winter','Nebensaison / Juli–August / Winter','Temporada baja / julio–agosto / invierno');
export default {
 url,booking:{kind:'form',url:booking,text:L('Appelez d’abord le 06 70 70 86 53 pour connaître les disponibilités. La page officielle demande ensuite la fiche d’inscription et un chèque d’arrhes de 60 €. Confirmez ces modalités avec l’école.','First call +33 6 70 70 86 53 for availability. The official page then requests a registration form and a €60 deposit cheque. Confirm these arrangements with the school.','Rufe zuerst +33 6 70 70 86 53 für freie Termine an. Laut offizieller Seite folgen Anmeldeformular und 60 € Anzahlung per Scheck. Bestätige das Vorgehen mit der Schule.','Llama primero al +33 6 70 70 86 53 para consultar disponibilidad. La página oficial pide después la ficha de inscripción y un cheque de señal de 60 €. Confirma estas condiciones con la escuela.')},
 contacts:[{label:'schoolContact',phone:'+33670708653',email:'osmose.kite@gmail.com'}],
 intro:L('Kitesurf et foil autour de La Franqui : groupes de trois élèves maximum, radio et sécurité bateau.','Kitesurf and foil around La Franqui: groups of at most three students, radio coaching and boat safety support.','Kite und Foil rund um La Franqui: höchstens drei Schüler, Funkbetreuung und Sicherungsboot.','Kitesurf y foil en La Franqui: grupos de tres alumnos como máximo, radio y embarcación de seguridad.'),
 about:L('Osmose travaille sur les spots de Leucate, La Franqui, Le Barcarès et La Palme, en collaboration avec KSL. Sa grille annonce un paiement en fin de cours ou de stage, selon le temps pratiqué dans un vent adapté.','Osmose uses spots at Leucate, La Franqui, Le Barcarès and La Palme, working with KSL. Its tariff page states payment at the end of the lesson or course according to time practised in suitable wind.','Osmose nutzt Spots in Leucate, La Franqui, Le Barcarès und La Palme in Zusammenarbeit mit KSL. Laut Preisseite erfolgt die Bezahlung am Kursende entsprechend der bei geeignetem Wind geübten Zeit.','Osmose utiliza spots de Leucate, La Franqui, Le Barcarès y La Palme en colaboración con KSL. Su página de tarifas indica pago al final del curso según el tiempo practicado con viento adecuado.'),
 aboutSource:url,
 spot:L('Base de pratique aux Coussoules à La Franqui ; le spot de la séance se confirme avec l’école. L’adresse postale indiquée pour les arrhes est 4 lotissement Les Petentous, route des Corbières, 11510 Treilles : ce n’est pas un rendez-vous de cours.','Teaching base at Les Coussoules in La Franqui; confirm the session’s spot with the school. The deposit postal address is 4 lotissement Les Petentous, route des Corbières, 11510 Treilles: it is not a lesson meeting point.','Unterrichtsbasis an den Coussoules in La Franqui; den jeweiligen Spot mit der Schule bestätigen. Postanschrift für die Anzahlung: 4 lotissement Les Petentous, route des Corbières, 11510 Treilles. Das ist kein Kurstreffpunkt.','Base de práctica en Les Coussoules, La Franqui; confirma el spot de la sesión con la escuela. La dirección postal para la señal es 4 lotissement Les Petentous, route des Corbières, 11510 Treilles: no es el punto de encuentro del curso.'),
 spotSource:booking,mapQuery:'Les Coussoules La Franqui Leucate France',
 courses:[
  course(L('Cours kitesurf','Kitesurf lesson','Kitesurfkurs','Curso kitesurf'),'130 € / 150 € / 100 €',seasons,prices,[hours(4)]),
  course(L('À partir de la 6e séance','From the 6th session','Ab der 6. Einheit','A partir de la 6. sesión'),'100 € / 110 € / 100 €',seasons,prices),
  course(L('Cours foil','Foil lesson','Foilkurs','Curso foil'),'130 € / 150 € / 100 €',seasons,prices,[L('Avec location du foil : 140 € / 160 € / 140 €.','Including foil rental: €140 / €160 / €140.','Mit Foilverleih: 140 € / 160 € / 140 €.','Con alquiler del foil: 140 € / 160 € / 140 €.')]),
  course(L('Location avec sécurité','Rental with safety support','Verleih mit Sicherheitsbetreuung','Alquiler con seguridad'),'70 €',hours(3),prices),
  course(L('Navigation accompagnée + matériel','Accompanied riding + equipment','Begleitetes Kiten + Material','Navegación acompañada + equipo'),'100 € / 110 € / 90 €',seasons,prices,[hours(4)]),
  course(L('Groupes et autres locations','Groups and other rentals','Gruppen und weiterer Verleih','Grupos y otros alquileres'),quote,L('Aile dès 50 € ; board + aile dès 100 €','Kite from €50; board + kite from €100','Kite ab 50 €; Board + Kite ab 100 €','Cometa desde 50 €; tabla + cometa desde 100 €'),prices)
 ],
 facts:[
  fact('schedule',L('Haute saison : juillet et août. Basse saison : 15 mars–30 juin et 1er septembre–15 novembre. Hiver : 1er décembre–15 mars, selon la grille officielle. Confirmez les créneaux par téléphone.','High season: July and August. Low season: 15 March–30 June and 1 September–15 November. Winter: 1 December–15 March, according to the official sheet. Confirm lesson slots by phone.','Hauptsaison: Juli und August. Nebensaison: 15. März–30. Juni und 1. September–15. November. Winter: 1. Dezember–15. März laut Preisliste. Termine telefonisch bestätigen.','Temporada alta: julio y agosto. Baja: 15 de marzo–30 de junio y 1 de septiembre–15 de noviembre. Invierno: 1 de diciembre–15 de marzo según la tabla oficial. Confirma horarios por teléfono.'),prices),
  fact('requirements',L('La responsabilité civile spécifique est obligatoire. La page de réservation donne accès aux documents de licence et à l’autorisation parentale pour les mineurs. Vérifiez les tarifs d’assurance actuels avant de souscrire.','Specific liability cover is compulsory. The booking page links licence documents and parental authorisation for minors. Check current insurance fees before enrolling.','Spezielle Haftpflichtversicherung ist Pflicht. Auf der Buchungsseite stehen Lizenzunterlagen und die elterliche Genehmigung für Minderjährige. Aktuelle Versicherungsbeiträge vor Abschluss prüfen.','La responsabilidad civil específica es obligatoria. La página de reserva enlaza documentos de licencia y autorización parental para menores. Comprueba las tarifas actuales del seguro antes de contratar.'),booking),
  fact('equipment',L('Le site présente initiation, perfectionnement, foil et mountainboard, ainsi que des photos et vidéos des séances. Le paiement selon le temps pratiqué ne supprime pas l’étape des arrhes indiquée à la réservation.','The site lists beginner lessons, progression, foil and mountainboard, plus lesson photos and videos. Payment according to time practised does not remove the deposit step stated in the booking instructions.','Die Website bietet Einstieg, Aufbaukurse, Foil und Mountainboard sowie Kursfotos und Videos. Die Abrechnung nach geübter Zeit ersetzt nicht die in den Buchungshinweisen genannte Anzahlung.','La web presenta iniciación, perfeccionamiento, foil y mountainboard, además de fotos y vídeos. El pago según tiempo practicado no elimina la señal indicada en las instrucciones de reserva.'),url)
 ],
 links:[{label:'insurance',url:booking},{label:'weather',url:url+'meteo/'},{label:'photos',url:url+'lecole-et-lesprit-osmose/photos/'}],
 sources:[{label:'official',url},{label:'prices',url:prices},{label:'form',url:booking}]
};
