import {L,course,fact,hours,sessions} from './common.mjs';
const url='https://www.sky-fly.com/',booking=url+'reservation-en-ligne.html',news=url+'news.html';
const rate=n=>L(`Dès ${n} €`,`From €${n}`,`Ab ${n} €`,`Desde ${n} €`,`Vanaf €${n}`);
export default {
 url,booking:{kind:'calendar',url:booking,text:L('Choisissez une date et une offre sur le site officiel. Le parcours indique disponibilité, confirmation et paiement sécurisé. Pour toute question ou problème de calendrier, appelez le 06 75 42 26 91.','Choose a date and offer on the official site. The flow provides availability, confirmation and secure payment. For questions or calendar problems, call +33 6 75 42 26 91.','Wähle Datum und Angebot auf der offiziellen Website. Dort erfolgen Verfügbarkeit, Bestätigung und sichere Zahlung. Bei Fragen oder Kalenderproblemen: +33 6 75 42 26 91.','Elige fecha y oferta en la web oficial. Allí encontrarás disponibilidad, confirmación y pago seguro. Para dudas o problemas del calendario, llama al +33 6 75 42 26 91.','Kies een datum en aanbod op de officiële site. Daar vind je beschikbaarheid, bevestiging en veilige betaling. Bij vragen of kalenderproblemen: +33 6 75 42 26 91.')},
 contacts:[{label:'schoolContact',phone:'+33675422691'}],
 intro:L('Un trajet en bateau vers l’île de la Rascasse, une zone d’apprentissage peu profonde et des cours guidés par radio.','A boat ride to Île de la Rascasse, shallow-water learning and radio-guided lessons.','Mit dem Boot zur Île de la Rascasse, Lernen im flachen Wasser und Funkbetreuung.','Un trayecto en barco a la Île de la Rascasse, aprendizaje en aguas poco profundas y clases por radio.','Met de boot naar Île de la Rascasse, leren in ondiep water en begeleiding via radio.'),
 about:L('SkyFly présente Sylvain Colson comme gérant. L’école propose kitesurf, wingfoil, kitefoil et planche tractée, avec équipement et transport bateau. Les offres comprennent cours individuels, collectifs et formule famille.','SkyFly lists Sylvain Colson as its manager. The school offers kitesurf, wingfoil, kitefoil and towed-board sessions with equipment and boat transport. Options include private lessons, groups and a family package.','SkyFly nennt Sylvain Colson als Leiter. Angeboten werden Kitesurf, Wingfoil, Kitefoil und bootsgezogene Boardsessions mit Ausrüstung und Bootstransport. Es gibt Einzel-, Gruppen- und Familienangebote.','SkyFly presenta a Sylvain Colson como gerente. Ofrece kitesurf, wingfoil, kitefoil y tabla remolcada con equipo y transporte en barco, en clases individuales, grupos y fórmula familiar.','SkyFly vermeldt Sylvain Colson als manager. De school biedt kitesurf, wingfoil, kitefoil en getrokken boardsessies met materiaal en bootvervoer. Er zijn privélessen, groepen en een familieformule.'),
 aboutSource:url,
 spot:L('Départ annoncé pour 2026 : Port Adhoc Port Leucate. Le site indique Rue Dali, 11370 Leucate. Certaines fiches d’offres affichent encore une ancienne adresse : confirmez votre rendez-vous avec SkyFly avant de partir.','Departure announced for 2026: Port Adhoc Port Leucate. The site lists Rue Dali, 11370 Leucate. Some offer pages still show an old address: confirm your meeting point with SkyFly before travelling.','Für 2026 angekündigter Startpunkt: Port Adhoc Port Leucate. Die Website nennt Rue Dali, 11370 Leucate. Manche Angebotsseiten zeigen noch eine alte Adresse: Treffpunkt vor der Anreise mit SkyFly bestätigen.','Salida anunciada para 2026: Port Adhoc Port Leucate. La web indica Rue Dali, 11370 Leucate. Algunas fichas aún muestran una dirección antigua: confirma el encuentro con SkyFly antes de salir.','Vertrekpunt aangekondigd voor 2026: Port Adhoc Port Leucate. De site vermeldt Rue Dali, 11370 Leucate. Sommige aanbodpagina’s tonen nog een oud adres: bevestig je afspreekpunt met SkyFly voor vertrek.'),
 spotSource:news,mapQuery:'Port Adhoc Port Leucate Rue Dali France',
 courses:[
  course(L('Découverte à deux','Discovery for two','Einstieg zu zweit','Descubrimiento para dos','Kennismaking voor twee'),rate(65),L('Par personne · 3 h · une aile pour deux','Per person · 3 hours · one kite shared by two','Pro Person · 3 Stunden · ein Kite für zwei','Por persona · 3 h · una cometa para dos','Per persoon · 3 uur · één kite voor twee'),url),
  course(L('Cours kitesurf','Kitesurf lesson','Kitesurfkurs','Clase de kitesurf','Kitesurfles'),rate(120),hours(3),url),
  course(L('Stage kitesurf','Kitesurf course','Kitesurfkurs-Paket','Curso de kitesurf','Kitesurfcursus'),rate(310),sessions(3,3),url),
  course(L('Initiation wingfoil','Wingfoil introduction','Wingfoil-Einstieg','Iniciación wingfoil','Wingfoil-introductie'),rate(100),hours(1),url),
  course(L('Initiation kitefoil','Kitefoil introduction','Kitefoil-Einstieg','Iniciación kitefoil','Kitefoil-introductie'),rate(80),hours(1),url),
  course(L('Planche tractée / strapless / surf','Towed board / strapless / surf','Gezogenes Board / Strapless / Surf','Tabla remolcada / strapless / surf','Getrokken board / strapless / surf'),rate(80),hours(1),url),
  course(L('Cours particulier','Private lesson','Privatkurs','Clase particular','Privéles'),rate(240),hours(3),url+'offres/cours-particulier-3-heures.html'),
  course(L('Tribu / famille','Tribe / family','Gruppe / Familie','Tribu / familia','Groep / familie'),rate(400),L('3 h · forfait pour 1 à 4 personnes','3 hours · package for 1–4 people','3 Stunden · Paket für 1–4 Personen','3 h · tarifa para 1–4 personas','3 uur · pakket voor 1–4 personen'),url+'offres/formule-tribu-famille.html',[L('La fiche officielle demande de sélectionner 1 personne pour réserver le forfait famille.','The official offer asks you to select 1 person when booking the family package.','Laut offizieller Angebotsseite bei Buchung des Familienpakets 1 Person auswählen.','La ficha oficial pide seleccionar 1 persona al reservar el paquete familiar.','De officiële aanbodpagina vraagt om 1 persoon te selecteren voor het familiepakket.')])
 ],
 facts:[
  fact('schedule',L('Horaires publiés : tous les jours, 10–19 h. La date, le créneau et le départ de votre activité se confirment dans la réservation et avec l’école.','Published opening hours: daily, 10:00–19:00. Confirm your activity date, slot and departure in the booking and with the school.','Veröffentlichte Öffnungszeiten: täglich 10–19 Uhr. Datum, Termin und Abfahrt deiner Aktivität über die Buchung und mit der Schule bestätigen.','Horario publicado: todos los días, 10–19 h. Confirma fecha, horario y salida en la reserva y con la escuela.','Gepubliceerde openingstijden: dagelijks 10–19 uur. Bevestig datum, tijd en vertrek via de boeking en bij de school.'),url),
  fact('requirements',L('Équipement fourni : combinaison, harnais, gilet et casque radio ; transport en bateau compris. Prévoir des chaussons néoprène. Consultez la page licence et assurance avant votre séance.','Equipment includes a wetsuit, harness, vest and radio helmet; boat transport is included. Bring neoprene boots. Read the licence and insurance page before your session.','Neoprenanzug, Trapez, Weste und Funkhelm sowie Bootstransport sind enthalten. Neoprenschuhe mitbringen. Vor der Session die Lizenz- und Versicherungsseite lesen.','Se incluyen neopreno, arnés, chaleco, casco con radio y barco. Lleva escarpines de neopreno. Consulta la página de licencia y seguro antes de la sesión.','Wetsuit, trapeze, vest, radiohelm en bootvervoer zijn inbegrepen. Neem neopreenschoenen mee. Lees voor je sessie de pagina over licentie en verzekering.'),url+'presentation/licence-et-assurance.html'),
  fact('prices',L('Les montants sont annoncés « à partir de » par SkyFly. La formule famille est un forfait, contrairement à la découverte à deux facturée par personne. Vérifiez le récapitulatif avant paiement.','SkyFly advertises these amounts as starting prices. The family option is a package, while discovery for two is priced per person. Check the summary before payment.','SkyFly nennt diese Beträge als Einstiegspreise. Das Familienangebot ist ein Paket, der Einstieg zu zweit wird pro Person berechnet. Vor Zahlung die Zusammenfassung prüfen.','SkyFly anuncia importes « desde ». La fórmula familiar es un paquete; el descubrimiento para dos se cobra por persona. Revisa el resumen antes de pagar.','SkyFly noemt dit vanafprijzen. De familieformule is een pakket; kennismaking voor twee is per persoon. Controleer het overzicht voor betaling.'),url)
 ],
 links:[{label:'form',url:url+'contact.html'},{label:'insurance',url:url+'presentation/licence-et-assurance.html'},{label:'photos',url},{label:'arrival',url:news}],
 sources:[{label:'official',url},{label:'arrival',url:news},{label:'calendar',url:booking}]
};
