import {L,course,fact,seasonal,hours,sessions} from './common.mjs';
const url='https://www.tendancekite.com/',booking=url+'book-online',prices=url+'tarifs-kitesurf';
export default {
 url,booking:{kind:'calendar',url:booking,text:L('Réservez les cours collectifs, locations et navigations surveillées dans le calendrier officiel. Paiement en ligne ou sur place selon l’option. Les cours particuliers se réservent uniquement par téléphone.','Book group lessons, rentals and supervised riding in the official calendar. Pay online or on site depending on the option. Private lessons are booked by telephone only.','Gruppenkurse, Verleih und beaufsichtigtes Kiten über den offiziellen Kalender buchen. Je nach Angebot online oder vor Ort bezahlen. Privatkurse nur telefonisch buchen.','Reserva grupos, alquileres y navegación supervisada en el calendario oficial. Pago en línea o presencial según la opción. Las clases particulares solo se reservan por teléfono.')},
 contacts:[{label:'schoolContact',phone:'+33662091703',email:'tendancekite@gmail.com'}],
 intro:L('À Port Mahon, Sigean, des séances de kitesurf sur un plan d’eau peu profond avec accès en bateau et radio individuelle.','At Port Mahon in Sigean, kitesurf sessions on shallow water with boat access and individual radios.','In Port Mahon bei Sigean: Kitesurfeinheiten im flachen Wasser mit Bootszugang und individuellen Funkgeräten.','En Port Mahon, Sigean, sesiones de kitesurf en aguas poco profundas con acceso en barco y radios individuales.'),
 about:L('Xavier Dumas, moniteur diplômé d’État et enseignant d’EPS, enseigne le kitesurf depuis 2010. Tendance Kite présente des groupes de quatre élèves maximum, avec une aile et une radio par personne, ainsi que des cours particuliers.','Xavier Dumas, a qualified instructor and physical-education teacher, has taught kitesurf since 2010. Tendance Kite lists groups of at most four students, each with a kite and radio, as well as private lessons.','Xavier Dumas, staatlich qualifizierter Lehrer und Sportlehrer, unterrichtet seit 2010 Kitesurf. Tendance Kite nennt Gruppen mit höchstens vier Schülern, eigenem Kite und Funkgerät sowie Privatkurse.','Xavier Dumas, instructor titulado y profesor de educación física, enseña kitesurf desde 2010. Tendance Kite presenta grupos de cuatro alumnos como máximo, cada uno con cometa y radio, además de clases particulares.'),
 aboutSource:url+'en',
 spot:L('Base au 1089 Port Mahon, 11130 Sigean. Accès au spot en bateau, parking, vestiaires et douche chaude indiqués par l’école. Confirmez le lieu et l’heure de votre séance dans la réservation.','Base at 1089 Port Mahon, 11130 Sigean. The school lists boat access to the spot, parking, changing rooms and a hot shower. Confirm your session’s meeting place and time when booking.','Basis: 1089 Port Mahon, 11130 Sigean. Die Schule nennt Bootszugang, Parkplatz, Umkleiden und warme Dusche. Treffpunkt und Uhrzeit bei der Buchung bestätigen.','Base en 1089 Port Mahon, 11130 Sigean. La escuela indica acceso al spot en barco, aparcamiento, vestuarios y ducha caliente. Confirma lugar y hora al reservar.'),
 spotSource:url+'en',mapQuery:'Tendance Kite 1089 Port Mahon Sigean France',
 courses:[
  course('Tendance Découverte','120 € / 140 €',seasonal,prices,[sessions(1,4)]),
  course('Tendance Initiation','230 € / 270 €',seasonal,prices,[sessions(2,4)]),
  course('Tendance Évolution','330 € / 390 €',seasonal,prices,[sessions(3,4)]),
  course('Tendance Glisse','430 € / 500 €',seasonal,prices,[sessions(4,4)]),
  course('Tendance Évasion','530 € / 600 €',seasonal,prices,[sessions(5,4)]),
  course(L('Cours particulier','Private lesson','Privatkurs','Clase particular'),'180 € / 200 €',seasonal,prices,[L('1 h dans l’eau, sur un créneau de 2 h. Réservation uniquement par téléphone.','1 hour in the water within a 2-hour slot. Telephone booking only.','1 Stunde im Wasser in einem Zeitfenster von 2 Stunden. Nur telefonisch buchbar.','1 h en el agua dentro de un horario de 2 h. Reserva solo por teléfono.')],'tel:+33662091703'),
  course(L('Navigation surveillée / location','Supervised riding / rental','Beaufsichtigtes Kiten / Verleih','Navegación supervisada / alquiler'),'40 € / 80 €',hours(4),prices,[L('40 € sans location ; 80 € avec équipement complet. Options : board +20 €, aile +20 €, foil +50 €.','€40 without rental; €80 with full equipment. Options: board +€20, kite +€20, foil +€50.','40 € ohne Verleih; 80 € mit kompletter Ausrüstung. Optionen: Board +20 €, Kite +20 €, Foil +50 €.','40 € sin alquiler; 80 € con equipo completo. Opciones: tabla +20 €, cometa +20 €, foil +50 €.')])
 ],
 facts:[
  fact('prices',L('Haute saison : juillet–août ; le premier montant est la basse saison. Les cours collectifs durent 4 h, préparation et trajet bateau compris. Matériel inclus dans les tarifs des cours.','High season: July–August; the first amount is low season. Group sessions last 4 hours including setup and boat transport. Lesson prices include equipment.','Hauptsaison: Juli–August; erster Betrag jeweils Nebensaison. Gruppeneinheiten dauern 4 Stunden einschließlich Vorbereitung und Bootstransport. Material ist im Kurspreis enthalten.','Temporada alta: julio–agosto; el primer importe es temporada baja. Las sesiones de grupo duran 4 h incluyendo preparación y barco. El material está incluido en los cursos.'),prices),
  fact('requirements',L('L’assurance spécifique kitesurf est obligatoire. Complétez la fiche d’inscription officielle, y compris après une réservation par téléphone, et confirmez les prérequis avec l’école.','Specific kitesurf insurance is compulsory. Complete the official registration form, including after telephone booking, and confirm participation requirements with the school.','Spezielle Kitesurfversicherung ist Pflicht. Auch nach telefonischer Buchung das offizielle Anmeldeformular ausfüllen und Voraussetzungen mit der Schule klären.','El seguro específico de kitesurf es obligatorio. Completa la inscripción oficial también si reservas por teléfono y confirma los requisitos con la escuela.'),booking),
  fact('schedule',L('Les cours sont réalisés et facturés lorsque les conditions le permettent. La FAQ officielle prévoit report ou remboursement en cas de départ après annulation météo. Moyens de paiement annoncés : carte, espèces, chèques, chèques vacances et virement instantané.','Lessons take place and are charged when conditions allow. The official FAQ provides postponement or refund if you leave after weather cancellation. Listed payments: card, cash, cheques, holiday vouchers and instant bank transfer.','Unterricht und Abrechnung erfolgen bei geeigneten Bedingungen. Laut FAQ gibt es bei Wetterausfall Verschiebung oder bei Abreise Erstattung. Genannte Zahlarten: Karte, bar, Scheck, Urlaubsgutscheine und Echtzeitüberweisung.','Las clases se realizan y cobran si las condiciones lo permiten. La FAQ contempla aplazamiento o reembolso si te marchas tras una cancelación meteorológica. Pagos publicados: tarjeta, efectivo, cheques, cheques vacaciones y transferencia instantánea.'),url+'en')
 ],
 links:[{label:'photos',url},{label:'calendar',url:booking},{label:'registration',url:url+'fiche-inscription'},{label:'lodging',url:url+'accomodation'},{label:'gift',url:url+'gift-card'}],
 sources:[{label:'official',url:url+'en'},{label:'prices',url:prices},{label:'calendar',url:booking}]
};
