import { mkdir,writeFile,cp,readdir,readFile,rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { build } from 'vite';
import { schools } from './schools.mjs';
const base='/kite-schools-showcase/';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow='<span aria-hidden="true">↗</span>';
for(const s of schools){
const offers=s.groups.map((g,i)=>`<button class="offer offer-${i}" data-course="${g.course}"><span class="offer-number">0${i+1}</span><h3>${g.name}</h3><p>${g.line}</p><div class="offer-bottom"><span>${g.meta}</span>${arrow}</div></button>`).join('');
const catalogue=[...new Set(s.courses.map(c=>c.group))].map(group=>`<details class="course-group"><summary>${group}<span>+</span></summary><div class="course-list">${s.courses.map((c,i)=>c.group===group?`<article class="course"><div><h4>${c.name}</h4><p>${c.duration}${c.note?' · '+esc(c.note):''}</p></div><div class="course-price"><strong>${c.price}</strong><button data-course="${i}" aria-label="Choisir : ${esc(c.name)}">Choisir ${arrow}</button></div></article>`:'').join('')}</div></details>`).join('');
const html=`<!doctype html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${s.name} — ${s.location}</title><meta name="description" content="${esc(s.intro)} ${s.eyebrow} à ${s.location}."><meta name="theme-color" content="${s.theme==='flight'?'#1029df':'#f5f1e8'}"><link rel="icon" href="data:image/svg+xml,${encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='24' fill='#173e4a'/><text x='50' y='67' font-family='Arial' font-size='37' font-weight='bold' text-anchor='middle' fill='white'>${s.mark}</text></svg>`)}"><link rel="preload" as="image" href="${base}riviera-images/${s.slug}.webp"><link rel="stylesheet" href="../src/style.css"></head><body class="${s.theme}"><a class="skip" href="#formules">Aller aux activités</a>
<header class="header"><a class="brand" href="#top" aria-label="${s.name} — accueil"><span class="brand-mark">${s.mark}</span><span class="brand-name">${s.name}<small>${s.location}</small></span></a><nav aria-label="Navigation principale"><a href="#formules">La glisse</a><a href="#pratique">L’école</a><a class="nav-cta" href="#reservation">Préparer ma sortie ${arrow}</a></nav></header>
<main><section class="hero" id="top"><div class="hero-media"><img class="hero-image" src="${base}riviera-images/${s.slug}.webp" width="2048" height="1152" fetchpriority="high" alt="Illustration de glisse sur la Méditerranée, créée par IA"><div class="scene" data-image="${s.slug}" aria-hidden="true"></div><div class="hero-shade"></div></div><div class="hero-copy"><p class="eyebrow">${s.eyebrow}</p><h1>${s.title.map(t=>`<span>${t}</span>`).join('')}</h1><p class="intro">${s.intro}</p><a class="button hero-cta" href="#formules">${s.theme==='flight'?'Trouver mon cours':'À vous de jouer'} ${arrow}</a></div><div class="hero-orbit" aria-hidden="true"><span>${s.theme==='island'?'la mer<br>en liberté':s.theme==='flight'?'FLIGHT<br>MODE':'43° N<br>06° E'}</span></div><div class="hero-foot"><span>${s.tag}</span><a href="#formules" aria-label="Découvrir les activités">↓</a><button class="motion" aria-pressed="false">Pause animation</button></div></section>
<div class="facts">${s.facts.map(f=>`<span>${f}</span>`).join('')}</div>
<section class="section offers-section" id="formules"><div class="section-heading"><p class="eyebrow">01 / Sur l’eau</p><h2>${s.section}</h2></div><div class="offers">${offers}</div><details class="all-courses"><summary>Toutes les formules & tarifs ${arrow}</summary><div class="catalogue">${s.slug==='issambres-kite-school'?'<p class="season-note">Prix basse / haute saison : 2 octobre–30 avril / 1er mai–1er octobre.</p>':''}${catalogue}</div></details></section>
<section class="section practical" id="pratique"><div class="section-heading"><p class="eyebrow">02 / L’essentiel</p><h2>${s.theme==='island'?'On se retrouve<br>au bord de l’eau.':'Le bon endroit.<br>Le bon moment.'}</h2></div><div class="practical-content">${s.practical.map(([q,a])=>`<details><summary>${q}<span>+</span></summary><p>${a}</p></details>`).join('')}</div></section>
<section class="section reservation" id="reservation"><div class="booking-intro"><p class="eyebrow">03 / Votre prochaine sortie</p><h2>Ça commence<br>par une envie.</h2><p>Choisissez une activité et une date souhaitée.</p><p class="demo-note">Démonstration — aucune demande envoyée, aucune place réservée.</p><a class="contact-inline" href="tel:${s.phone}">Parler à l’école ${arrow}</a></div><form id="booking-form" novalidate><div class="form-top"><span class="step-name">Votre sortie</span><span class="booking-progress">01 / 03</span></div>
<fieldset data-step="0"><legend class="sr-only">Votre sortie</legend><label>Votre formule<select name="course">${s.courses.map((c,i)=>`<option value="${i}">${c.name}</option>`).join('')}</select></label><p class="selected-price" aria-live="polite"></p>${s.bases?`<label>Votre base<select name="base">${s.bases.map(b=>`<option>${b}</option>`).join('')}</select></label>`:''}${s.gift?'<label>Votre envie<select name="kind"><option value="session">Une sortie pour moi / nous</option><option value="gift">Offrir un bon cadeau</option></select></label>':''}<div class="date-choice"><div class="calendar"><div class="calendar-head"><button type="button" data-month="-1" aria-label="Mois précédent">←</button><strong class="calendar-month"></strong><button type="button" data-month="1" aria-label="Mois suivant">→</button></div><div class="calendar-weekdays" aria-hidden="true"></div><div class="calendar-days" aria-label="Date souhaitée"></div></div><label>Date souhaitée<input type="date" name="date" required></label><p class="field-note">Préférence uniquement. Disponibilités et météo à confirmer.</p></div><p class="gift-note" hidden>${s.slug==='kitesurf-evasion'?'Bon valable du 1er avril au 15 septembre de l’année en cours. Confirmez la validité avec Hervé.':s.slug==='airxkite'?'Validité e-foil : un an, en saison. Autres activités : à confirmer avec l’équipe.':'Bon personnalisé : activité, montant et validité à convenir avec Stéphane.'}</p><button type="button" class="button" data-next>Continuer ${arrow}</button></fieldset>
<fieldset data-step="1" hidden><legend class="sr-only">Vos coordonnées</legend><div class="form-grid"><label>Votre nom<input name="name" autocomplete="name" required maxlength="100"></label><label>E-mail<input name="email" type="email" autocomplete="email" required maxlength="160"></label><label>Téléphone<input name="phone" type="tel" autocomplete="tel" maxlength="40"></label><label>Participants<input name="people" type="number" min="1" max="12" value="1" required></label></div><label>Votre niveau<select name="level"><option>Débutant</option><option>Premiers bords</option><option>Autonome</option><option>À discuter</option></select></label><label>Une précision ? <span class="optional">(facultatif)</span><textarea name="message" rows="2" maxlength="1000" placeholder="Votre activité, un pack de plusieurs séances…"></textarea></label><p class="field-note">Ces informations restent dans cette page et sont effacées à la fin de la démonstration.</p><div class="form-actions"><button type="button" class="back" data-back>← Retour</button><button type="button" class="button" data-next>Vérifier ${arrow}</button></div></fieldset>
<fieldset data-step="2" hidden><legend class="sr-only">Récapitulatif</legend><h3 class="review-heading" tabindex="-1">Votre envie prend forme.</h3><dl class="booking-summary"></dl><p class="demo-note">Ceci est un aperçu. Rien ne sera transmis à l’école.</p><div class="form-actions"><button type="button" class="back" data-back>← Modifier</button><button type="button" class="button" data-finish>Terminer la démo ${arrow}</button></div></fieldset>
<div class="booking-complete" hidden tabindex="-1" role="status"><span class="complete-mark" aria-hidden="true">↗</span><h3>À bientôt sur l’eau.</h3><p>La démonstration est terminée.<br>Aucune réservation n’a été envoyée.</p><a class="button" href="tel:${s.phone}">Contacter l’école ${arrow}</a><button class="back" type="button" data-reset>Recommencer</button></div></form></section>
</main><footer><div class="footer-top"><div><p class="eyebrow">${s.name}</p><h2>On en parle ?</h2></div><div class="footer-contact"><a href="tel:${s.phone}">${s.phoneLabel} ${arrow}</a>${s.secondPhone?`<a class="secondary-phone" href="tel:${s.secondPhone.number}">${s.secondPhone.label} ${arrow}</a>`:''}<a class="email" href="mailto:${s.email}">${s.email}</a>${s.slug==='airxkite'?'<a class="email" href="https://wa.me/33660418734" target="_blank" rel="noopener">WhatsApp ↗</a>':s.slug==='kite-foil-school'||s.slug==='issambres-kite-school'?`<a class="email" href="sms:${s.phone}">Envoyer un SMS ↗</a>`:''}</div></div><div class="footer-bottom"><p>${s.address.replace('\n','<br>')}</p><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.map)}" target="_blank" rel="noopener">Itinéraire ${arrow}</a><details class="privacy"><summary>À propos de cette page</summary><p>Visuel d’ambiance créé par IA. Formulaire de démonstration : aucune réservation ni collecte de données. Sans traceur publicitaire.</p></details><a href="#top" aria-label="Retour en haut">↑</a></div></footer><script id="school-data" type="application/json">${JSON.stringify(s).replaceAll('<','\\u003c')}</script><script type="module" src="../src/app.js"></script></body></html>`;
await mkdir(`riviera-site/${s.slug}`,{recursive:true});await writeFile(`riviera-site/${s.slug}/index.html`,html);
}
const input=Object.fromEntries(schools.map(s=>[s.slug,resolve(`riviera-site/${s.slug}/index.html`)]));
await build({configFile:false,root:resolve('riviera-site'),base,publicDir:false,build:{outDir:resolve('riviera-dist'),emptyOutDir:true,assetsDir:'riviera-assets',rollupOptions:{input,output:{manualChunks(id){if(id.includes('node_modules/three/'))return 'riviera-three';}}}}});
await rm('riviera-assets',{recursive:true,force:true});
for(const name of await readdir('riviera-dist'))await cp(`riviera-dist/${name}`,name,{recursive:true});
console.log('Built four isolated Riviera sites; root and old school files not touched.');
