const c=(group,name,duration,price,note='',extra={})=>({group,name,duration,price,note,...extra});
export const schools=[
{
slug:'kite-foil-school',theme:'nautical',name:'Kite Foil School',mark:'KFS',location:'Saint-Raphaël',eyebrow:'Kite · Wing · Catamaran',title:['Le large,','pour horizon.'],intro:'Une aile, une planche. Ou une journée sous voiles.',tag:'Port Santa Lucia · Côte d’Azur',section:'À chacun son large.',phone:'+33745208043',phoneLabel:'07 45 20 80 43',email:'kitefoilschool@gmail.com',contactName:'L’équipe Kite Foil School',address:'Port Santa Lucia · Quai n°8, bassin Nord\n120 place du Club Nautique · 83700 Saint-Raphaël',map:'Port Santa Lucia Quai 8 120 Place du Club Nautique Saint-Raphaël',facts:['Kite · 4 débutants maximum','Wing · 3 débutants maximum','Départ du port Santa Lucia'],groups:[{name:'Kitesurf',line:'Vos premiers bords.',meta:'Stages & progression',course:0},{name:'Wingfoil',line:'L’envie de décoller.',meta:'Apprentissage en petit groupe',course:3},{name:'Catamaran',line:'La journée s’étire.',meta:'Coucher de soleil & croisières',course:6}],
courses:[c('Kitesurf','Stage débutant kite','3 séances','À confirmer','4 débutants maximum.',{max:4}),c('Kitesurf','Cours de kite','À la séance','À confirmer','Débutants et progression.',{max:4}),c('Kitesurf','Navigation surveillée kite','Avec ou sans matériel','À confirmer','Niveau requis à valider avec l’équipe.'),c('Wingfoil','Stage débutant wingfoil','3 séances','À confirmer','3 débutants maximum.',{max:3}),c('Wingfoil','Cours de wingfoil','À la séance','À confirmer','3 débutants maximum.',{max:3}),c('Wingfoil','Glisse / foil tracté','À confirmer','À confirmer'),c('Catamaran','Coucher de soleil','2 h','À confirmer','À bord du Sea Rider. Privatisation à préciser.',{max:12}),c('Catamaran','Dîner au coucher de soleil','3 h','À confirmer','Repas à bord ; formule à confirmer.',{max:10}),c('Catamaran','Journée découverte','6 h','À confirmer','Itinéraire choisi selon les conditions.',{max:12}),c('Catamaran','Grande journée découverte','7 h','À confirmer','Programme et repas à préciser.',{max:12}),c('Catamaran','Croisière Saint-Tropez','2 jours','À confirmer','Programme et équipage à convenir.',{max:12}),c('Matériel','Conseil surf shop','Sur rendez-vous','Sur demande')],
practical:[['Le rendez-vous','Quai n°8, bassin Nord du port Santa Lucia. Le lieu et l’horaire sont confirmés avant la sortie.'],['Kite & wing','Cours avec Seb. Privilégiez le SMS pendant les heures sur l’eau. Licence et assurance à prévoir ; modalités à confirmer avec l’équipe.'],['Catamaran','Sea Rider, Lagoon 40. Sorties en Méditerranée de mai à octobre. Pour les croisières : 06 10 97 55 85. Programme, repas et capacité selon la formule.'],['Tarifs & météo','Les tarifs exacts dépendent de la formule. Le créneau est confirmé selon la météo et le niveau. Aucun horaire ni place n’est garanti par ce calendrier.']],secondPhone:{number:'+33610975585',label:'Catamaran · 06 10 97 55 85'},gift:false
},
{
slug:'kitesurf-evasion',theme:'escape',name:'Kitesurf Évasion',mark:'É.',location:'Saint-Aygulf',eyebrow:'Kite · Wing · Multiglisse',title:['Prenez','la tangente.'],intro:'Du premier décollage au prochain défi, avec Hervé Rousseau.',tag:'Saint-Aygulf · Fréjus · Saint-Raphaël',section:'Quel sera votre terrain de jeu ?',phone:'+33615144569',phoneLabel:'06 15 14 45 69',email:'herve@kitesurf-evasion.fr',contactName:'Hervé',address:'Plage de Saint-Aygulf · Fréjus\nPoint de rendez-vous confirmé avec Hervé',map:'Plage de Saint Aygulf Fréjus',facts:['Coaching radio','Découverte & perfectionnement','Kite · wing · parawing · dockstart'],groups:[{name:'Kitesurf',line:'L’appel du vent.',meta:'2 h · 90 €',course:0},{name:'Wing & foil',line:'Changez de dimension.',meta:'2 h · 90 €',course:7},{name:'Multiglisse',line:'Ne choisissez plus.',meta:'10 séances · 1 200 €',course:14}],
courses:[c('Kitesurf','Découverte kite','2 h','90 €'),c('Kitesurf','Cours / progression kite','3 h','145 €'),c('Kitesurf','Stage kite · 3 séances','3 × 3 h','420 €'),c('Kitesurf','Stage kite · 5 séances','5 × 3 h','620 €'),c('Kitesurf','Stage kite · 9 séances','9 × 3 h','920 €'),c('Kitesurf','Cours privé kite','2 h 30','300 € solo / 400 € duo','Prix total du cours, pas par personne.',{max:2}),c('Kitesurf','Location kite + planche / foil','2 h 30','110 €','Niveau d’autonomie à valider.'),c('Wing & foil','Wing / parawing / dockstart','2 h','90 €','4 élèves maximum.',{max:4}),c('Wing & foil','Découverte wing / foil','3 h','145 €','4 élèves maximum.',{max:4}),c('Wing & foil','Progression wing / foil','3 h','140 €'),c('Wing & foil','Stage wing / foil · 3 séances','3 × 3 h','420 €'),c('Wing & foil','Stage wing / foil · 5 séances','5 × 3 h','620 €'),c('Wing & foil','Stage wing / foil · 9 séances','9 × 3 h','920 €'),c('Wing & foil','Foil tracté','1 h','150 €'),c('Multiglisse','Forfait multiglisse','10 séances','1 200 €','Individuel ou familial.'),c('Wing & foil','Cours privé wing / foil','2 h 30','300 € solo / 400 € duo','Prix total du cours.',{max:2}),c('Wing & foil','Location wing / foil','2 h 30','110 €'),c('Autres envies','E-foil / forfait Gold ou Silver','À préciser','Sur demande'),c('Matériel','Conseil matériel / boutique','Sur demande','À confirmer')],
practical:[['Le spot','Base à Saint-Aygulf, dans la baie de Fréjus. Le point de départ et les conditions sont confirmés avec Hervé.'],['À prévoir','Licence FFVL obligatoire. Assurance journée proposée sur place ; modalités à confirmer. Location de combinaison : 5 €.'],['Bons cadeaux','Personnalisables, pour les différentes activités. Validité indiquée : du 1er avril au 15 septembre de l’année en cours. Confirmez la date avant tout achat.'],['Le bon format','Cours, stages, location, séances privées ou forfait multiglisse familial. Les séances s’adaptent au niveau et à la météo.']],gift:true
},
{
slug:'issambres-kite-school',theme:'island',name:'Issambres Kite School',mark:'iks',location:'Les Issambres',eyebrow:'Kitesurf · Wingfoil · E-foil',title:['Un peu d’air.','Beaucoup de liberté.'],intro:'Avec Stéphane, la Méditerranée devient votre terrain de glisse.',tag:'Les Issambres · Golfe de Saint-Tropez',section:'Votre rythme. Votre glisse.',phone:'+33745078245',phoneLabel:'07 45 07 82 45',email:'iks.azur@gmail.com',contactName:'Stéphane',address:'Port de San Peïre · Les Issambres\n83380 Roquebrune-sur-Argens',map:'Port San Peire Les Issambres',facts:['Toute l’année','Cours privés & semi-privés','Coaching depuis le bateau'],groups:[{name:'Kite & wing',line:'À votre rythme.',meta:'Privé · 2 h · 170 / 250 €',course:0},{name:'E-foil',line:'La mer, en douceur.',meta:'Dès 150 € / heure',course:5},{name:'Navigation',line:'L’espace de progresser.',meta:'Dès 60 / 80 €',course:3}],
courses:[c('Kite & wing','Cours particulier kite / wing','2 h','170 / 250 €','Basse / haute saison. 3 cours : 480 / 720 €. 5 cours : 750 / 1 150 €.',{max:1,low:170,high:250}),c('Kite & wing','Cours semi-particulier kite / wing','2 h 30','130 / 200 €','Basse / haute saison. 3 cours : 360 / 570 €. 5 cours : 550 / 900 €. Base tarifaire à confirmer pour votre groupe.',{max:2,low:130,high:200}),c('Kite & wing','Cours en groupe','3 h','Sur demande'),c('Navigation','Navigation surveillée','Dépose en bateau','60 / 80 €','Basse / haute saison. 3 sorties : 150 / 210 €. 5 sorties : 200 / 300 €. Autonomie validée après un cours.',{low:60,high:80}),c('Navigation','Navigation + location','Dépose en bateau','100 / 150 €','Basse / haute saison. 3 sorties : 280 / 420 €. 5 sorties : 430 / 660 €. Autonomie requise.',{low:100,high:150}),c('E-foil','Foil électrique','1 h','Dès 150 €','3 × 1 h : dès 420 €. 5 × 1 h : dès 660 €.')],
practical:[['Deux saisons, deux tarifs','Basse saison : 2 octobre–30 avril. Haute saison : 1er mai–1er octobre. Les deux prix sont indiqués dans cet ordre.'],['Ce qui est inclus','Combinaison, matériel de sécurité et coaching bateau sont inclus dans les tarifs. Pour la navigation surveillée, l’autonomie doit être validée après un cours.'],['Le rendez-vous','Départ des Issambres, secteur port de San Peïre / base de voile. Stéphane confirme le point précis et choisit le spot selon les conditions.'],['Parlons de votre sortie','Cours privés, semi-privés, groupes sur demande et bons cadeaux personnalisés. Envoyez un SMS si Stéphane est sur l’eau : il vous rappelle.']],gift:true
},
{
slug:'airxkite',theme:'flight',name:'AirXKite',mark:'AXK',location:'Saint-Raphaël & Cannes',eyebrow:'École de kite & wing depuis 2001',title:['L’eau en bas.','Vous, au‑dessus.'],intro:'Deux bases. Du premier vol aux bords qui s’enchaînent.',tag:'Saint-Raphaël ↔ Cannes–Mandelieu',section:'Choisissez votre décollage.',phone:'+33660418734',phoneLabel:'06 60 41 87 34',email:'info@airxkite.com',contactName:'L’équipe AirXKite',address:'Saint-Raphaël · Quai n°8 du port\nCannes · Port du Béal, 110 boulevard du Midi',map:'Airxkite Saint Raphael Quai 8',facts:['École labellisée EFK','Mars → octobre','Cours en pleine eau'],groups:[{name:'Kitesurf',line:'Cap sur vos premiers bords.',meta:'3 h 30 · 150 €',course:0},{name:'Wingfoil',line:'Un nouveau point de vue.',meta:'3 h · 150 €',course:4},{name:'E-foil',line:'Décollage tout en douceur.',meta:'Cannes · 1 h 30 · 150 € solo',course:11}],
courses:[c('Kitesurf','Leçon collective kite','3 h 30','150 €','4 élèves maximum sur l’eau.',{max:4}),c('Kitesurf','Stage initiation kite','3 × 3 h 30 sur 2 jours','420 €','Deux journées consécutives.'),c('Kitesurf','Pack 3 cours kite','3 × 3 h 30','420 €'),c('Kitesurf','Pack 5 cours kite','5 × 3 h 30','650 €'),c('Wingfoil','Leçon collective wingfoil','3 h','150 €','4 élèves maximum.',{max:4}),c('Wingfoil','Stage / pack 3 cours wing','3 × 3 h','420 €'),c('Wingfoil','Stage / pack 5 cours wing','5 × 3 h','650 €'),c('Cours privés','Cours privé kite / kitefoil / wing','2 h','300 €','Une personne.',{max:1}),c('Cours privés','Cours duo kite / kitefoil / wing','2 h 30','200 € / personne','Deux participants.',{min:2,max:2}),c('Foil tracté','Foil tracté solo','1 h','150 €',{},{max:1}),c('Foil tracté','Foil tracté duo','2 h 30','200 € / personne','Deux participants.',{min:2,max:2}),c('E-foil','E-foil solo','1 h 30','150 €','Cannes–Mandelieu, dès 12 ans.',{max:1,base:'Cannes–Mandelieu'}),c('E-foil','E-foil duo','1 h 30','280 € au total','Cannes–Mandelieu, dès 12 ans.',{min:2,max:2,base:'Cannes–Mandelieu'}),c('Navigation','Navigation surveillée kite sans matériel','3 h','90 €','Savoir tirer des bords des deux côtés.'),c('Navigation','Navigation kite / wing avec location','3 h','110 €','Niveau requis à confirmer.'),c('Paddle','Location paddle','1 h / demi-journée / journée','15 / 30 / 50 €','Carte 10 h : 130 €.',{base:'Cannes–Mandelieu'}),c('Paddle','Cours paddle','1 h','50 € (1–2) / 100 € (3–4)','Tarif selon la taille du groupe.',{max:4,base:'Cannes–Mandelieu'}),c('Paddle','Balade aux îles en paddle','3 h','85 €','2 personnes minimum. Base tarifaire à confirmer.',{min:2,base:'Cannes–Mandelieu'}),c('Autres envies','Tandem kite / kitetrip / groupes','À préciser','Sur demande'),c('Matériel','Matériel neuf & occasion','Conseil boutique','Sur demande','Stock et prix à confirmer avec l’équipe.')],
practical:[['Choisir sa base','Kite, wing et foil tracté : Saint-Raphaël ou Cannes–Mandelieu. E-foil et paddle présentés ici : Cannes–Mandelieu. Accueil uniquement sur rendez-vous.'],['Où nous retrouver','Saint-Raphaël : quai n°8 du port, 83700. Cannes : port du Béal, 110 boulevard du Midi, 06150 Cannes la Bocca. Le point précis est confirmé par l’équipe.'],['Votre session','Ouverture de mars à octobre. Départ en bateau, cours selon la météo et le niveau. Licence et assurance à prévoir pour le kite et le wing ; modalités à confirmer.'],['Offrir & s’équiper','Bons cadeaux pour les activités. Pour l’e-foil : validité d’un an, utilisation en saison. Autres validités à confirmer. Matériel neuf et occasion sur demande, sans stock affiché en temps réel.']],gift:true,bases:['Saint-Raphaël','Cannes–Mandelieu']
}
];
// Notes and source URLs are maintained separately; no original-site URLs enter visitor pages.
for(const s of schools)for(const course of s.courses)if(typeof course.note!=='string')course.note='';
