const {chromium}=require('playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const {checkSourceContent,checkEnquiryDraft}=require('./content-checks.cjs');
const base=process.env.VENT_TEST_BASE||'http://127.0.0.1:4174/kite-schools-showcase/';
const schoolSlugs=['kitepulsion','narbonne-kite-passion','addicted2kite','osmose-kite','chinook','skyfly','coriolis','tendance-kite','ksl','akila-gruissan'];
(async()=>{
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const page=await context.newPage();let pageErrors=[];let failedResources=[];
page.on('pageerror',e=>pageErrors.push(e.message));
page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(base))failedResources.push({url:r.url(),status:r.status()});});
const report={base,pages:[],checks:[],errors:[],network:[]};
const routes=['',...schoolSlugs.flatMap(slug=>(slug==='skyfly'?['fr','en','de','es','nl']:['fr','en','de','es']).map(l=>slug+'/'+(l==='fr'?'':l+'.html')))];
for(const route of routes){
 await page.goto(base+route,{waitUntil:'domcontentloaded'});
 await page.evaluate(async()=>{const images=[...document.images];images.forEach(im=>im.loading='eager');await Promise.all(images.map(im=>im.decode().catch(()=>{})));await document.fonts.ready;});
 await page.waitForFunction(()=>document.querySelector('.scene')?.dataset.rendered==='true');
 const result=await page.evaluate(()=>({title:document.title,h1:document.querySelector('h1')?.textContent.trim(),width:document.documentElement.scrollWidth,viewport:innerWidth,lang:document.documentElement.lang,broken:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src),courseCount:document.querySelectorAll('.session-item').length,emptyLinks:[...document.querySelectorAll('a')].filter(a=>!a.getAttribute('href')).length,badAnchors:[...document.querySelectorAll('a[href^="#"]')].map(a=>a.getAttribute('href')).filter(h=>h!=='#'&&!document.getElementById(h.slice(1))),three:document.querySelector('.scene')?.dataset.rendered}));
 assert.ok(result.h1,'missing headline: '+route);assert.equal(result.broken.length,0,'broken images: '+route+' '+result.broken.join(','));assert.ok(result.width<=result.viewport,'overflow: '+route);assert.equal(result.badAnchors.length,0,'bad anchor: '+route);assert.equal(result.three,'true','Three.js not rendered: '+route);
 if(route){assert.ok(result.courseCount>=3,'missing courses: '+route);await checkSourceContent(page,route,report);}
 report.pages.push({route,...result});
}
report.checks.push('All 42 routes: rendered headline, images, anchors, no desktop overflow, Three.js canvas.');
await page.goto(base,{waitUntil:'domcontentloaded'});
await page.locator('[data-filter="foil"]').click();assert.equal(await page.locator('.school-card:visible').count(),8);await page.locator('[data-filter="beginner"]').click();assert.equal(await page.locator('.school-card:visible').count(),9);await page.locator('[data-filter="all"]').click();assert.equal(await page.locator('.school-card:visible').count(),10);report.checks.push('School filters: foil 8, first-time 9, all 10.');
await page.locator('[data-finder]').first().click();await page.locator('input[name="sport"][value="foil"]').check();await page.locator('#finder-form button[type="submit"]').click();assert.equal(await page.locator('.finder-result').count(),3);await page.keyboard.press('Escape');assert.equal(await page.locator('.finder-dialog').evaluate(d=>d.open),false);report.checks.push('Finder: beginner + foil recommendations; Escape closes modal and restores focus.');
await page.locator('.map-pin[data-school="6"]').click();assert.equal(await page.locator('#map-name').textContent(),'Coriolis Foil School');assert.match(await page.locator('#map-link').getAttribute('href'),/coriolis/);report.checks.push('Interactive map updates school image, copy, and link.');
await page.goto(base+'kitepulsion/',{waitUntil:'domcontentloaded'});await page.locator('[data-course="0"]').click();assert.equal(await page.locator('.course-dialog').evaluate(d=>d.open),true);assert.match(await page.locator('.course-dialog-content h2').textContent(),/carte/);assert.equal(await page.locator('.course-dialog-content a.button').getAttribute('href'),'mailto:kitepulsion@gmail.com');await page.keyboard.press('Escape');await page.locator('.faq-list summary').first().click();assert.equal(await page.locator('.faq-list details').first().evaluate(d=>d.open),true);report.checks.push('Course details show full features and official booking link; FAQ expands.');
await page.locator('.motion-toggle').click();assert.equal(await page.locator('body').evaluate(b=>b.classList.contains('motion-off')),true);await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('body').evaluate(b=>b.classList.contains('motion-off')),true);report.checks.push('Motion toggle persists across page reload.');
await page.setViewportSize({width:390,height:844});
for(const route of routes){await page.goto(base+route,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);const mobile=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,heading:(()=>{const r=document.createRange();r.selectNodeContents(document.querySelector('h1'));return r.getBoundingClientRect().toJSON();})(),hero:document.querySelector('.school-hero,.collection-hero').getBoundingClientRect().toJSON()}));assert.ok(mobile.width<=mobile.viewport,'mobile overflow: '+route+' '+mobile.width);assert.ok(mobile.heading.right<=mobile.viewport+1,'heading clipped: '+route);assert.ok(mobile.heading.left>=-1,'heading clipped left: '+route);}
report.checks.push('All 42 routes: no horizontal overflow or clipped headlines at 390px.');
await page.goto(base+'skyfly/nl.html',{waitUntil:'domcontentloaded'});await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');await page.locator('.site-nav nav a[href="#formules"]').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');assert.equal(await page.locator('.next-school').getAttribute('href'),'/kite-schools-showcase/coriolis/en.html');report.checks.push('Mobile menu opens, follows section, closes; Dutch next-school link falls back to English.');
const reduced=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const rp=await reduced.newPage();await rp.goto(base,{waitUntil:'domcontentloaded'});assert.equal(await rp.locator('body').evaluate(b=>b.classList.contains('motion-off')),true);await reduced.close();report.checks.push('System reduced-motion preference respected.');
const fallback=await browser.newContext({viewport:{width:390,height:844}});await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type.includes('webgl'))return null;return original.call(this,type,...args);};});const fp=await fallback.newPage();await fp.goto(base,{waitUntil:'domcontentloaded'});await fp.waitForTimeout(1500);assert.ok(await fp.locator('.scene-image').first().evaluate(i=>i.complete&&i.naturalWidth>0));assert.ok(await fp.locator('h1').isVisible());await fallback.close();report.checks.push('WebGL unavailable: static hero image and all content remain usable.');
await checkEnquiryDraft(page,base,report);
report.errors=pageErrors;report.network=failedResources;assert.equal(pageErrors.length,0,'JavaScript errors '+pageErrors.join(';'));assert.equal(failedResources.length,0,'Failed resources '+JSON.stringify(failedResources));report.passed=true;
fs.writeFileSync('.verification/audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:true,pages:report.pages.length,checks:report.checks,errors:pageErrors,network:failedResources},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
