import { writeFile, mkdir, cp, readdir } from 'node:fs/promises';
import { schools } from './schools.mjs';
import { locales } from './locales.mjs';
import { contentFor, languagesFor, reviewedOn, uiFor } from './verified-content.mjs';
const root='/kite-schools-showcase/';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14M12 5l7 7-7 7" stroke="currentColor" stroke-width="1.5"/></svg>';
const compass='<svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="m20 2 5 13 13 5-13 5-5 13-5-13L2 20l13-5z" fill="currentColor"/><circle cx="20" cy="20" r="4" fill="var(--paper,#f5f3eb)"/></svg>';
const img=(name,cls='',alt='',eager=false)=>`<img class="${cls}" src="/images/${name}.webp" srcset="/images/${name}-sm.webp 800w, /images/${name}.webp 2048w" sizes="${eager?'(max-width: 600px) 1600px, 100vw':cls==='card-image'?'(max-width: 700px) 100vw, 50vw':'100vw'}" alt="${esc(alt)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async" width="2048" height="1152">`;
const head=(title,desc,lang='en',image='coast')=>`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f5f3eb"><meta name="robots" content="noindex"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:image" content="https://wrappedsuperclass.github.io${root}images/${image}.webp"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=DM+Sans:wght@400;450;500;550;600;650;700;800&family=DM+Serif+Display:ital@0;1&display=swap" rel="stylesheet"><link rel="stylesheet" href="/src/style.css"></head>`;
const script=`<script type="module" src="/src/app.js"></script></body></html>`;
function home(){return `${head('VENT — Follow the feeling. | 10 kite schools, South of France','Ten independent kite schools. One wild stretch of Mediterranean coastline. Find your next session.')}<body class="collection-page"><a class="skip-link" href="#schools">Skip to schools</a>
<header class="site-nav collection-nav"><a href="${root}" class="collection-logo" aria-label="VENT home">${compass}<span>VENT<span class="logo-sub">THE KITE SCHOOL COLLECTION</span></span></a><nav aria-label="Main navigation"><a href="#schools">The schools <sup>10</sup></a><a href="#coastline">The coastline</a><button class="nav-cta" data-finder>Find my school ${arrow}</button></nav><button class="menu-toggle" aria-label="Open menu" aria-expanded="false"><span></span><span></span></button></header>
<main><section class="collection-hero" aria-labelledby="hero-title">${img('coast','scene-image','Aerial coastal mood image of turquoise water and a wild sandy shoreline',true)}<div class="scene" data-scene="coast" aria-hidden="true"></div><div class="hero-shade"></div><div class="hero-topline"><span><i class="status-dot"></i> SOUTH OF FRANCE · MEDITERRANEAN SOUL</span><span>43° N &nbsp; 03° E</span></div><div class="collection-hero-copy"><p class="eyebrow">LESS ORDINARY. MORE ALIVE.</p><h1 id="hero-title">FOLLOW<br>THE <em>FEELING.</em></h1><div class="hero-copy-bottom"><p>Salt on your skin. Wind in your hands.<br>Find the school that feels like you.</p><a href="#schools" class="button button-lime">Explore the schools ${arrow}</a></div></div><a href="#coastline" class="hero-postcard"><span class="postcard-mark">${compass}</span><span>One coastline.<br><b>Endless possibilities.</b></span><span class="postcard-arrow">↗</span></a><div class="hero-bottomline"><span>10 INDEPENDENT SCHOOLS</span><span>FROM NARBONNE TO LEUCATE</span><a href="#schools">SCROLL TO EXPLORE ↓</a></div></section>
<section class="collection-intro section-wrap" id="schools"><div class="section-index">01 / THE COLLECTION</div><div><h2>Your next chapter<br>starts <em>on the water.</em></h2><p>From quiet lagoons to wide-open sea. Ten schools with ten different personalities, brought together by the same love of the wind.</p></div><div class="intro-note">A little salt.<br>A little courage.<br><span>A whole lot of freedom.</span>${compass}</div></section>
<div class="filter-bar section-wrap"><div class="filter-options" role="group" aria-label="Filter schools"><button class="filter active" data-filter="all" aria-pressed="true">All schools <span>10</span></button><button class="filter" data-filter="beginner" aria-pressed="false">First time?</button><button class="filter" data-filter="kite" aria-pressed="false">Kitesurf</button><button class="filter" data-filter="foil" aria-pressed="false">Wing & foil</button><button class="filter" data-filter="progression" aria-pressed="false">Level up</button></div><span class="filter-count" aria-live="polite">10 places to feel alive</span></div>
<section class="school-grid section-wrap" aria-label="The ten schools">${schools.map((s,i)=>`<article class="school-card theme-${s.theme}" data-tags="${s.tags.join(' ')}"><a class="card-main" href="${root}${s.slug}/" aria-label="Explore ${esc(s.name)}"><div class="card-photo">${img(s.image,'card-image',`${s.name} — ${s.tagline} (AI-generated mood imagery)`)}<span class="card-number">${String(i+1).padStart(2,'0')}</span><span class="card-category">${s.category}</span><div class="card-wordmark">${s.logo}</div><span class="card-open">${arrow}</span></div><div class="card-caption"><div><h3>${s.name}</h3><p>${s.short}</p></div><span>${s.place}<i>↗</i></span></div></a></article>`).join('')}</section>
<section class="finder-banner section-wrap"><span class="finder-symbol">${compass}</span><div><p class="eyebrow">YOUR KIND OF WATER</p><h2>Not sure where to start?</h2><p>Two quick choices. A school that fits your rhythm.</p></div><button class="button button-dark" data-finder>Find my school ${arrow}</button></section>
<section class="coast-section" id="coastline"><div class="coast-head section-wrap"><p class="section-index">02 / THE COASTLINE</p><h2>One coast.<br><em>A thousand ways to feel it.</em></h2><p>A pocket of the South of France where the Tramontane meets the Mediterranean. Pick a point on the coast. Find your people.</p></div><div class="coast-layout section-wrap"><div class="coast-map" aria-label="Illustrated school locator"><span class="map-label map-land">LA NARBONNAISE</span><span class="map-label map-sea">MÉDITERRANÉE</span><svg viewBox="0 0 700 700" preserveAspectRatio="none" aria-hidden="true"><path d="M490 -20C470 90 525 90 500 145S465 203 450 250 450 300 417 337 446 412 405 464 440 535 400 587 440 650 385 730H-20V-20Z" fill="#e4e4d4"/><path d="M490 -20C470 90 525 90 500 145S465 203 450 250 450 300 417 337 446 412 405 464 440 535 400 587 440 650 385 730" stroke="#f7f2db" stroke-width="15" fill="none"/><path d="M245 158q-60 30-10 112t50-18q45-55 15-100zM314 316q-24 18-12 82t28-8q28-55-16-74M335 485q-48 50-17 145t23-16q20-69-6-129" fill="#99beb6"/><path d="M195 0Q180 140 225 277T288 457T317 710" stroke="#c7c6b1" stroke-dasharray="5 7" fill="none" stroke-width="2"/></svg><span class="map-north">N ↑</span>${schools.map((s,i)=>`<button class="map-pin ${i===0?'active':''}" style="left:${s.pin[0]}%;top:${s.pin[1]}%" data-school="${i}" aria-label="${esc(s.name)}, ${s.place}" aria-pressed="${i===0}">${String(i+1).padStart(2,'0')}</button>`).join('')}<span class="map-disclaimer">ILLUSTRATED LOCATOR · NOT TO SCALE</span></div><div class="map-school" aria-live="polite"><div class="map-school-photo">${img(schools[0].image,'',schools[0].name)}</div><div class="map-school-body"><p class="eyebrow" id="map-location">${schools[0].place} / ${schools[0].spot}</p><h3 id="map-name">${schools[0].name}</h3><p id="map-description">${schools[0].short}</p><a class="text-link" id="map-link" href="${root}${schools[0].slug}/">Explore this school ${arrow}</a></div></div></div></section>
<section class="closing section-wrap"><p class="eyebrow">GO ON. FOLLOW IT.</p><h2>See you<br><em>out there.</em><span>↗</span></h2><a class="button button-dark" href="#schools">Find your next session ${arrow}</a></section></main>
<footer class="collection-footer section-wrap"><a href="${root}" class="collection-logo">${compass} VENT</a><p>10 schools. One love for the wind.<br><span>Independent website redesign collection · AI-generated mood imagery.</span></p><button class="motion-toggle" aria-pressed="false">Motion <span>On</span></button><a href="https://github.com/WrappedSuperClass/kite-schools-showcase" target="_blank" rel="noopener">About the project ↗</a></footer>
<dialog class="finder-dialog" aria-labelledby="finder-heading"><button class="dialog-close" aria-label="Close school finder">×</button><div class="finder-content"><p class="eyebrow">FIND YOUR PEOPLE</p><h2 id="finder-heading">What’s your<br><em>kind of session?</em></h2><form id="finder-form"><fieldset><legend>01 / Where are you starting?</legend><label class="choice"><input type="radio" name="level" value="beginner" checked><span>My first time <small>Curious, excited, ready to try.</small></span><i>↗</i></label><label class="choice"><input type="radio" name="level" value="progression"><span>I already ride <small>New skills. New sensations.</small></span><i>↗</i></label></fieldset><fieldset><legend>02 / What are you drawn to?</legend><div class="sport-choices"><label class="choice"><input type="radio" name="sport" value="kite" checked><span>Kitesurf</span></label><label class="choice"><input type="radio" name="sport" value="foil"><span>Wing & foil</span></label></div></fieldset><button class="button button-dark" type="submit">Show my schools ${arrow}</button></form><div class="finder-results" hidden aria-live="polite"></div></div></dialog><script type="application/json" id="collection-data">${JSON.stringify(schools).replace(/</g,'\\u003c')}</script>${script}`;}
const external=url=>/^https?:/.test(url)?' target="_blank" rel="noopener"':'';
const source=(url,label)=>`<a class="source-link" href="${esc(url)}"${external(url)}>${esc(label)} ↗</a>`;
function schoolPage(s,lang,index){
 const d=contentFor(s,lang), t=locales[lang], u=uiFor(lang), headlines=s[lang]||s.en;
 const langs=languagesFor(s.slug),next=schools[(index+1)%schools.length],num=String(index+1).padStart(2,'0');
 const aboutTitle=lang==='fr'?s.aboutTitle:[t.intro,t.chapter];
 const checked=new Intl.DateTimeFormat(lang,{dateStyle:'long',timeZone:'UTC'}).format(new Date(reviewedOn+'T12:00:00Z'));
 const primary=`<a class="button button-accent" data-booking href="${esc(d.booking.url)}"${external(d.booking.url)}>${esc(d.booking.label)} ${arrow}</a>`;
 const draftEmail=d.contacts.find(c=>c.email)?.email;
 const photo=`<img src="/school-photos/${s.slug}.jpg" alt="${esc(u.archivePhoto+' — '+s.name)}" loading="lazy" decoding="async">`;
 return `${head(d.title,d.meta,lang,s.image)}<body class="school-page theme-${s.theme} layout-${s.layout}" style="--accent:${s.accent};--ink:${s.ink}"><a class="skip-link" href="#formules">${t.courses}</a><div class="collection-bar"><a href="${root}">← VENT / ${t.collection}</a><span>${num} / 10 <i>—</i> ${s.place.toUpperCase()}</span><div class="lang-switch" aria-label="${t.choose}">${langs.map(l=>`<a ${l===lang?'aria-current="page"':''} href="${root}${s.slug}/${l==='fr'?'':l+'.html'}" hreflang="${l}" lang="${l}">${l.toUpperCase()}</a>`).join('')}</div></div>
<header class="site-nav school-nav"><a class="school-logo" href="#top">${s.logo}</a><nav aria-label="Navigation"><a href="#ecole">${t.school}</a><a href="#formules">${t.courses}</a><a href="#practical">${u.practicalLabel}</a><a href="#contact" class="nav-cta">${t.book} ${arrow}</a></nav><button class="menu-toggle" aria-label="${t.menu}" aria-expanded="false"><span></span><span></span></button></header>
<main><section class="school-hero" id="top"><div class="school-hero-visual">${img(s.image,'scene-image',u.imageLabel,true)}<div class="scene" data-scene="${s.image}" aria-hidden="true"></div><div class="hero-shade"></div><div class="hero-coordinates">${s.place}<span>${s.category.toUpperCase()}</span></div></div><div class="school-hero-copy"><p class="eyebrow"><span class="small-line"></span> ${s.place.toUpperCase()} · ${t.season.toUpperCase()}</p><h1><span>${headlines[0]}</span><em>${headlines[1]}</em></h1><p class="school-hero-sub">${esc(d.intro)}</p><div class="school-hero-actions"><a class="button button-accent" href="#formules">${t.learn} ${arrow}</a><a class="hero-secondary" href="#contact">${t.book} ↗</a></div></div><div class="school-hero-stamp">${compass}<span>${s.spot.toUpperCase()}</span></div><div class="school-hero-footer"><span>${esc(u.imageLabel)}</span><a href="#ecole">${t.scroll.toUpperCase()} ↓</a></div></section>
<div class="ticker" aria-hidden="true"><div>${Array(4).fill(`<span>${s.place}</span><i>✳</i><span>${s.category}</span><i>✳</i><span>${t.travel}</span><i>✳</i>`).join('')}</div></div>
<div class="content-review section-wrap"><span>${u.reviewed} <time datetime="${reviewedOn}">${checked}</time></span><a href="#sources">${u.sources} ↗</a></div>
<section class="school-about section-wrap" id="ecole"><div class="about-image reveal">${photo}<a class="photo-caption" href="${esc(d.aboutSource)}"${external(d.aboutSource)}>${u.archivePhoto} / ${u.source} ↗</a><div class="about-seal">${compass}<span>${s.place}<br>MÉDITERRANÉE</span></div></div><div class="about-copy"><p class="section-index">01 / ${t.about.toUpperCase()}</p><h2>${esc(aboutTitle[0])}<br><em>${esc(aboutTitle[1])}</em></h2>${d.about.map(p=>`<p>${esc(p)}</p>`).join('')}${source(d.aboutSource,u.source)}<a class="text-link" href="#contact">${t.request} ${arrow}</a></div></section>
<section class="sessions-section" id="formules"><div class="section-wrap"><div class="sessions-heading"><div><p class="section-index">02 / ${t.courses.toUpperCase()}</p><h2>${t.sessionTitle}</h2></div><p>${t.sessionText}</p></div>${d.priceReferenceYear?`<p class="dated-price-notice">${esc(d.priceNote)}</p>`:''}<div class="session-list">${d.courses.map((c,i)=>`<article class="session-item"><div class="session-number">${String(i+1).padStart(2,'0')}</div><div class="session-copy"><h3>${esc(c.name)}</h3><p>${esc(c.features[0]||c.unit)}</p>${source(c.url,u.source)}</div><div class="session-price">${esc(c.price)}<span>${esc(c.unit)}</span></div><button class="session-open" data-course="${i}" aria-label="${esc(t.more+' — '+c.name)}">${arrow}</button></article>`).join('')}</div><p class="price-note">${esc(d.priceNote)} ${source(d.url,u.official)}</p>${d.referenceRates?`<details class="reference-rates"><summary>${u.reference2022}</summary><p>${u.seasons}</p><table><caption>${u.reference2022}</caption><tbody>${d.referenceRates.map(r=>`<tr><th scope="row">${esc(r.name)}</th><td>${esc(r.price)}</td></tr>`).join('')}</tbody></table>${source(d.referenceSource,u.source)}</details>`:''}</div></section>
<section class="spot-section" id="spot"><div class="spot-visual">${img(s.image,'',u.imageLabel)}<div class="spot-image-overlay"></div><span class="spot-big-word">${s.place}</span><span class="spot-coordinate">${esc(u.imageLabel)}</span></div><div class="spot-copy section-wrap"><div><p class="section-index">03 / ${t.spotLabel.toUpperCase()}</p><h2>${s.spot}<em>${s.place}</em></h2></div><div><p>${esc(d.spot)}</p>${source(d.spotSource,u.source)}<a class="text-link" href="${esc(d.mapUrl)}" target="_blank" rel="noopener">${t.maps} ${arrow}</a></div></div></section>
<section class="practical-section section-wrap" id="practical"><div class="practical-heading"><p class="section-index">04 / ${u.practicalLabel.toUpperCase()}</p><h2>${u.practical}</h2></div><div class="practical-grid">${d.facts.map(f=>`<article class="practical-item"><h3>${esc(f.label)}</h3><p>${esc(f.text)}</p>${source(f.url,u.source)}</article>`).join('')}</div>${d.team?`<div class="school-team"><h3>${u.team}</h3><ul>${d.team.map(p=>`<li><strong>${esc(p.name)}</strong><span>${esc(p.role)}</span></li>`).join('')}</ul>${source(d.url,u.source)}</div>`:''}<div class="school-resources">${d.links.map(l=>`<a href="${esc(l.url)}"${external(l.url)}>${esc(l.label)} <span>↗</span></a>`).join('')}</div></section>
<section class="faq-section section-wrap"><div><p class="section-index">05 / ${t.faqLabel.toUpperCase()}</p><h2>${t.faq}</h2></div><div class="faq-list">${d.faq.map(f=>`<details><summary>${esc(f.q)}<span>+</span></summary><p>${esc(f.a)}<br>${source(f.url,u.source)}</p></details>`).join('')}</div></section>
<section class="contact-section" id="contact"><div class="contact-inner section-wrap"><p class="eyebrow">${s.name.toUpperCase()} / ${s.place.toUpperCase()}</p><h2>${u.bookingTitle}</h2><div class="contact-bottom"><p>${esc(d.booking.text)}</p>${primary}</div><div class="contact-links">${d.contacts.map(c=>`<article class="contact-card"><h3>${esc(c.label)}</h3>${c.phone?`<a href="tel:${esc(c.phone)}">${u.phoneContact}<span>${esc(c.phone)} ↗</span></a>`:''}${c.email?`<a href="mailto:${esc(c.email)}">${u.emailContact}<span>${esc(c.email)} ↗</span></a>`:''}${c.whatsapp?`<a href="${esc(c.whatsapp)}" target="_blank" rel="noopener">WhatsApp <span>↗</span></a>`:''}</article>`).join('')}</div>${draftEmail?`<details class="enquiry-compose"><summary>${u.draftTitle}</summary><p>${u.draftNote}</p><form data-enquiry-form data-email="${esc(draftEmail)}"><label>${u.name}<input name="name" required autocomplete="name" maxlength="100"></label><label>${u.dates}<input name="dates" required maxlength="100"></label><label class="enquiry-message">${u.message}<textarea name="message" required rows="4" maxlength="1500"></textarea></label><button class="button button-accent" type="submit">${u.draftTitle} ↗</button><div class="draft-result" hidden><p role="status">${u.draftReady}</p><textarea readonly aria-label="${u.draftTitle}" rows="7"></textarea></div></form></details>`:''}</div>${compass}</section>
<section class="sources-section section-wrap" id="sources"><div><p class="section-index">${u.source}</p><h2>${u.sources}</h2><p>${u.reviewed} <time datetime="${reviewedOn}">${checked}</time></p></div><ul>${d.sources.map(v=>`<li>${source(v.url,v.label)}<span>${esc(new URL(v.url).hostname)}</span></li>`).join('')}</ul></section>
<a class="next-school section-wrap" href="${root}${next.slug}/${lang==='fr'?'':(languagesFor(next.slug).includes(lang)?lang:'en')+'.html'}"><span>${t.next} / ${String((index+1)%10+1).padStart(2,'0')}</span><strong>${next.name}</strong>${arrow}</a></main>
<footer class="school-footer section-wrap"><div><a href="${root}" class="collection-logo">${compass} VENT</a><p>${t.demo}</p></div><button class="motion-toggle" aria-pressed="false" data-label="${t.motion}" data-on="${t.on}" data-off="${t.off}">${t.motion} <span>${t.on}</span></button><a href="${root}">← ${t.back}</a></footer><a href="#contact" class="mobile-book">${t.book} ${arrow}</a><dialog class="course-dialog" aria-labelledby="course-heading"><button class="dialog-close" aria-label="${t.close}">×</button><div class="course-dialog-content"></div></dialog><script id="school-data" type="application/json">${JSON.stringify({school:{...s,url:d.url,booking:d.booking},courses:d.courses,priceNote:d.priceNote,t,u,lang}).replace(/</g,'\\u003c')}</script>${script}`;
}
await mkdir('site/public',{recursive:true});
await writeFile('site/public/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#143d3d"/><path d="m32 7 7 18 18 7-18 7-7 18-7-18L7 32l18-7z" fill="#d4f76a"/></svg>');
await writeFile('site/public/.nojekyll','');
await writeFile('site/index.html',home());
for(let i=0;i<schools.length;i++){const s=schools[i];await mkdir(`site/${s.slug}`,{recursive:true});for(const lang of languagesFor(s.slug))await writeFile(`site/${s.slug}/${lang==='fr'?'index':lang}.html`,schoolPage(s,lang,i));}
if(!process.argv.includes('--templates-only')){
 const {build}=await import('vite'); await build();
 for(const file of await readdir('site-dist'))await cp(`site-dist/${file}`,file,{recursive:true});
 console.log('Published build to repository root: 42 pages, ten school identities.');
}
