export const schools = [
 {slug:'kitepulsion',name:'Kitepulsion',logo:'KITEPULSION',place:'La Franqui',spot:'Les Coussoules',image:'kitepulsion',theme:'volt',layout:'impact',accent:'#d4f76a',ink:'#101d20',tags:['kite','progression'],category:'Kitesurf · Freestyle',tagline:'Turn the wind into instinct.',coord:'42.94° N / 3.03° E',url:'http://kitepulsion.com/',short:'Big beach. Bigger possibilities.',fr:['LE VENT.','LA VIE.'],en:['MORE WIND.','MORE LIFE.'],de:['MEHR WIND.','MEHR LEBEN.'],es:['MÁS VIENTO.','MÁS VIDA.'],aboutTitle:['Le goût du vent.','Depuis toujours.'],aboutImage:'akila',pin:[57,60]},
 {slug:'narbonne-kite-passion',name:'Narbonne Kite Passion',logo:'narbonne kite passion',place:'La Nautique',spot:'Étang de Bages',image:'narbonne',theme:'lagoon',layout:'editorial',accent:'#c4dcba',ink:'#284d45',tags:['kite','beginner'],category:'Kitesurf · Lagoon',tagline:'A little closer to nature.',coord:'43.14° N / 3.01° E',url:'https://narbonnekitepassion.com/',short:'Your own little corner of the lagoon.',fr:['Le vent,','en douceur.'],en:['Find your','natural rhythm.'],de:['Dein ganz','eigener Rhythmus.'],es:['Encuentra','tu ritmo natural.'],aboutTitle:['Un peu de vent.','Beaucoup de liberté.'],aboutImage:'tendance',pin:[37,23]},
 {slug:'addicted2kite',name:'Addicted2kite',logo:'addicted2kite',place:'Narbonne-Plage',spot:'Le Créneau Naturel',image:'addicted',theme:'sunset',layout:'poster',accent:'#f36a3d',ink:'#38281f',tags:['kite','foil','progression'],category:'Kitesurf · Wingfoil',tagline:'One session is never enough.',coord:'43.15° N / 3.16° E',url:'https://addicted2kite.webflow.io/',short:'Good people. Endless sessions.',fr:['ENCORE','UNE SESSION.'],en:['ONE MORE','SESSION.'],de:['NOCH EINE','SESSION.'],es:['UNA SESIÓN','MÁS.'],aboutTitle:['Une passion.','Zéro demi-mesure.'],aboutImage:'akila',pin:[74,15]},
 {slug:'osmose-kite',name:'Osmose Kite',logo:'osmose',place:'La Franqui',spot:'Les Coussoules Basses',image:'osmose',theme:'deep',layout:'immersive',accent:'#d5efba',ink:'#173c35',tags:['kite','foil','beginner'],category:'Kitesurf · Kitefoil',tagline:'In sync with the elements.',coord:'42.93° N / 3.04° E',url:'http://www.osmose-kite.com/',short:'Let the elements set the pace.',fr:['Ne faire qu’un.','Avec le vent.'],en:['At one.','With the wind.'],de:['Eins sein.','Mit dem Wind.'],es:['Ser uno.','Con el viento.'],aboutTitle:['Le bon moment.','La bonne sensation.'],aboutImage:'narbonne',pin:[52,56]},
 {slug:'chinook',name:'Chinook Kite School',logo:'CHINOOK',place:'La Palme',spot:'Étang de La Palme',image:'chinook',theme:'heritage',layout:'editorial',accent:'#d56238',ink:'#583925',tags:['kite','beginner'],category:'Kitesurf · Since 1999',tagline:'Some things only get better.',coord:'42.97° N / 3.02° E',url:'https://www.chinook-leucate.com/',short:'Old-school soul. Wide-open water.',fr:['Les pieds dans l’eau.','L’esprit ailleurs.'],en:['Feet in the water.','Mind miles away.'],de:['Füße im Wasser.','Kopf ganz frei.'],es:['Pies en el agua.','Mente en otra parte.'],aboutTitle:['Le kite se transmet.','La passion aussi.'],aboutImage:'ksl',pin:[48,43]},
 {slug:'skyfly',name:'SkyFly Kiteschool',logo:'skyfly',place:'Port Leucate',spot:'Île de la Rascasse',image:'skyfly',theme:'sky',layout:'impact',accent:'#c0def5',ink:'#1751ad',tags:['kite','foil','beginner'],category:'Kitesurf · Wingfoil',tagline:'Your next stop? Up.',coord:'42.83° N / 3.02° E',url:'https://www.sky-fly.com/',short:'An island. A kite. Your kind of escape.',fr:['PRENEZ','LE LARGE.'],en:['TAKE','FLIGHT.'],de:['HEB','AB.'],es:['ALZA','EL VUELO.'],nl:['KIES','HET LUCHTRUIM.'],aboutTitle:['Une île pour apprendre.','Le ciel pour limite.'],aboutImage:'narbonne',pin:[41,85]},
 {slug:'coriolis',name:'Coriolis Foil School',logo:'coriolis↗',place:'Port Leucate',spot:'Port Leucate',image:'coriolis',theme:'foil',layout:'technical',accent:'#c5b5f4',ink:'#303045',tags:['foil','progression'],category:'Wingfoil · Kitefoil',tagline:'A different plane of existence.',coord:'42.85° N / 3.04° E',url:'https://coriolisfoilschool.fr/',short:'Less resistance. More possibility.',fr:['LA GLISSE.','EN APESANTEUR.'],en:['LESS WATER.','MORE AIR.'],de:['WENIGER WASSER.','MEHR LUFT.'],es:['MENOS AGUA.','MÁS AIRE.'],aboutTitle:['Une autre dimension.','À portée de foil.'],aboutImage:'osmose',pin:[53,77]},
 {slug:'tendance-kite',name:'Tendance Kite',logo:'tendance kite',place:'Sigean',spot:'Port Mahon',image:'tendance',theme:'wild',layout:'editorial',accent:'#c6c990',ink:'#3a5136',tags:['kite','beginner'],category:'Kitesurf · Nature',tagline:'Go where you feel most alive.',coord:'43.06° N / 2.97° E',url:'https://www.tendancekite.com/',short:'Wild surroundings. A softer landing.',fr:['Dehors.','Enfin.'],en:['Outside.','At last.'],de:['Draußen.','Endlich.'],es:['Al aire libre.','Por fin.'],aboutTitle:['Apprendre autrement.','Naturellement.'],aboutImage:'chinook',pin:[25,36]},
 {slug:'ksl',name:'Kite Surf Leucate',logo:'KSL / LEUCATE',place:'La Franqui',spot:'Les Coussoules',image:'ksl',theme:'club',layout:'club',accent:'#d8e3eb',ink:'#192e54',tags:['kite','foil','progression'],category:'Kitesurf · The club',tagline:'The sea brings us together.',coord:'42.94° N / 3.04° E',url:'https://www.kite-surf-leucate.com/',short:'Come for the kite. Stay for the club.',fr:['LA MER.','ET LES NÔTRES.'],en:['THE SEA.','OUR PEOPLE.'],de:['DAS MEER.','UNSERE LEUTE.'],es:['EL MAR.','LOS NUESTROS.'],aboutTitle:['Plus qu’une école.','Un point de ralliement.'],aboutImage:'kitepulsion',pin:[63,57]},
 {slug:'akila-gruissan',name:'Akila Gruissan',logo:'AKILA',place:'Gruissan',spot:'Plage des Chalets',image:'akila',theme:'race',layout:'poster',accent:'#fa6a38',ink:'#282b29',tags:['kite','foil','progression'],category:'Kitesurf · Wind Valley',tagline:'Made for the open water.',coord:'43.09° N / 3.12° E',url:'https://www.akila-centers.com/centres-outdoor/akila-gruissan/pole-mer/',short:'A legendary spot. Your next story.',fr:['PLEIN VENT.','PLEINE VIE.'],en:['FULL WIND.','FULL LIFE.'],de:['VOLLER WIND.','VOLLES LEBEN.'],es:['VIENTO A TOPE.','VIDA A TOPE.'],aboutTitle:['La Wind Valley.','Votre terrain de jeu.'],aboutImage:'addicted',pin:[70,31]}
];
